<?php
/**
 * FunctionServiceDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 子商户管理
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Mer\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * FunctionServiceDTO Class Doc Comment
 *
 * @category Class
 * @description 服务资质信息
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FunctionServiceDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FunctionServiceDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'shareScene' => 'string',
        'shareCertificate' => 'string',
        'wechatBackupCount' => 'string',
        'alipayBackupCount' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'shareScene' => null,
        'shareCertificate' => null,
        'wechatBackupCount' => null,
        'alipayBackupCount' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shareScene' => 'shareScene',
        'shareCertificate' => 'shareCertificate',
        'wechatBackupCount' => 'wechatBackupCount',
        'alipayBackupCount' => 'alipayBackupCount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shareScene' => 'setShareScene',
        'shareCertificate' => 'setShareCertificate',
        'wechatBackupCount' => 'setWechatBackupCount',
        'alipayBackupCount' => 'setAlipayBackupCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shareScene' => 'getShareScene',
        'shareCertificate' => 'getShareCertificate',
        'wechatBackupCount' => 'getWechatBackupCount',
        'alipayBackupCount' => 'getAlipayBackupCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shareScene'] = isset($data['shareScene']) ? $data['shareScene'] : null;
        $this->container['shareCertificate'] = isset($data['shareCertificate']) ? $data['shareCertificate'] : null;
        $this->container['wechatBackupCount'] = isset($data['wechatBackupCount']) ? $data['wechatBackupCount'] : null;
        $this->container['alipayBackupCount'] = isset($data['alipayBackupCount']) ? $data['alipayBackupCount'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shareScene
     *
     * @return string
     */
    public function getShareScene()
    {
        return $this->container['shareScene'];
    }

    /**
     * Sets shareScene
     *
     * @param string $shareScene <p>请根据实际场景选择分账code码<br />分账场景code<br />请参考<a>https://kdocs.cn/l/ctL732mNVN8C</a></p>
     *
     * @return $this
     */
    public function setShareScene($shareScene)
    {
        $this->container['shareScene'] = $shareScene;

        return $this;
    }

    /**
     * Gets shareCertificate
     *
     * @return string
     */
    public function getShareCertificate()
    {
        return $this->container['shareCertificate'];
    }

    /**
     * Sets shareCertificate
     *
     * @param string $shareCertificate <p>分账证明资质文件请参考https://kdocs.cn/l/ctL732mNVN8C</p>
     *
     * @return $this
     */
    public function setShareCertificate($shareCertificate)
    {
        $this->container['shareCertificate'] = $shareCertificate;

        return $this;
    }

    /**
     * Gets wechatBackupCount
     *
     * @return string
     */
    public function getWechatBackupCount()
    {
        return $this->container['wechatBackupCount'];
    }

    /**
     * Sets wechatBackupCount
     *
     * @param string $wechatBackupCount <div id=\"app\" class=\"global-wrap\"> <div class=\"ant-spin-nested-loading\"> <div class=\"ant-spin-container\"> <div id=\"global-content-id\" class=\"global-content\"> <div class=\"Product-wrap\" data-v-d3b69e56=\"\"> <section id=\"components-layout\" class=\"pc ant-layout\" data-v-d3b69e56=\"\"> <section class=\"ant-layout ant-layout-has-sider\" data-v-d3b69e56=\"\"> <section class=\"ant-layout\" data-v-d3b69e56=\"\"> <div id=\"feedback-wrap\" class=\"product-wrap\" data-v-d3b69e56=\"\"> <div class=\"ant-spin-nested-loading\" data-v-30c39a7a=\"\" data-v-d3b69e56=\"\"> <div class=\"ant-spin-container\"> <div class=\"Product-wrap\" data-v-30c39a7a=\"\"> <div class=\"ant-row\" data-v-30c39a7a=\"\"> <div class=\"ant-col ant-col-sm-24 ant-col-md-24 ant-col-lg-24\" data-v-30c39a7a=\"\"> <div class=\"renderMarkdown-wrap\" data-v-30c39a7a=\"\">可以输入0~20以内正整数（包含20）</div> </div> </div> </div> </div> </div> </div> </section> </section> </section> </div> </div> </div> </div> <div class=\"feedback\" data-v-3895cf46=\"\">&nbsp;</div> </div> <div>&nbsp;</div>
     *
     * @return $this
     */
    public function setWechatBackupCount($wechatBackupCount)
    {
        $this->container['wechatBackupCount'] = $wechatBackupCount;

        return $this;
    }

    /**
     * Gets alipayBackupCount
     *
     * @return string
     */
    public function getAlipayBackupCount()
    {
        return $this->container['alipayBackupCount'];
    }

    /**
     * Sets alipayBackupCount
     *
     * @param string $alipayBackupCount <p>可以输入0~20以内正整数（包含20）</p> <p>&nbsp;</p>
     *
     * @return $this
     */
    public function setAlipayBackupCount($alipayBackupCount)
    {
        $this->container['alipayBackupCount'] = $alipayBackupCount;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


