<?php
/**
 * IdentityAuthFinanceInstitutionInfo
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 子商户管理
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Mer\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * IdentityAuthFinanceInstitutionInfo Class Doc Comment
 *
 * @category Class
 * @description 金融机构信息
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IdentityAuthFinanceInstitutionInfo implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'IdentityAuthFinanceInstitutionInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'financeType' => 'string',
        'financeLicensePics' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'financeType' => null,
        'financeLicensePics' => 'string'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'financeType' => 'financeType',
        'financeLicensePics' => 'financeLicensePics'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'financeType' => 'setFinanceType',
        'financeLicensePics' => 'setFinanceLicensePics'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'financeType' => 'getFinanceType',
        'financeLicensePics' => 'getFinanceLicensePics'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['financeType'] = isset($data['financeType']) ? $data['financeType'] : null;
        $this->container['financeLicensePics'] = isset($data['financeLicensePics']) ? $data['financeLicensePics'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['financeType'] === null) {
            $invalidProperties[] = "'financeType' can't be null";
        }
        if ($this->container['financeLicensePics'] === null) {
            $invalidProperties[] = "'financeLicensePics' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets financeType
     *
     * @return string
     */
    public function getFinanceType()
    {
        return $this->container['financeType'];
    }

    /**
     * Sets financeType
     *
     * @param string $financeType <div data-page-id=\"DrEgd5UiTolweFx1SI4cl1jUnRg\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-VHxwd1AjgojDxaxR2ufcC2nunI6\">金融机构类型</div> <div class=\"ace-line ace-line old-record-id-VHxwd1AjgojDxaxR2ufcC2nunI6\">&nbsp;</div> <div class=\"ace-line ace-line old-record-id-VHxwd1AjgojDxaxR2ufcC2nunI6\"> <div data-page-id=\"DrEgd5UiTolweFx1SI4cl1jUnRg\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-D6WSdr3pboEP8xxZPSbcApZCnkc\">BANK_AGENT：银行业, 适用于商业银行、政策性银行、农村合作银行、村镇银行、开发性金融机构等 PAYMENT_AGENT：支付机构, 适用于非银行类支付机构 INSURANCE：保险业, 适用于保险、保险中介、保险代理、保险经纪等保险类业务 TRADE_AND_SETTLE：交易及结算类金融机构, 适用于交易所、登记结算类机构、银行卡清算机构、资金清算中心等 OTHER：其他金融机构, 适用于财务公司、信托公司、金融资产管理公司、金融租赁公司、汽车金融公司、贷款公司、货币经纪公司、消费金融公司、证券业、金融控股公司、股票、期货、货币兑换、小额贷款公司、金融资产管理、担保公司、商业保理公司、典当行、融资租赁公司、财经咨询等其他金融业务</div> </div> </div> </div>
     *
     * @return $this
     */
    public function setFinanceType($financeType)
    {
        $this->container['financeType'] = $financeType;

        return $this;
    }

    /**
     * Gets financeLicensePics
     *
     * @return string[]
     */
    public function getFinanceLicensePics()
    {
        return $this->container['financeLicensePics'];
    }

    /**
     * Sets financeLicensePics
     *
     * @param string[] $financeLicensePics <div data-page-id=\"KBYAdcPY0o40NUxAVK6cmsVcn6d\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-OlZrdWHKIoUqszxbrFwcK5zcnke\">金融机构许可证图片</div> <div class=\"ace-line ace-line old-record-id-OlZrdWHKIoUqszxbrFwcK5zcnke\">1、根据所属金融机构类型的许可证要求提供。</div> <div class=\"ace-line ace-line old-record-id-OlZrdWHKIoUqszxbrFwcK5zcnke\">2、请提供为&ldquo;申请商家主体&rdquo;所属的许可证，可授权使用总公司/分公司的特殊资质。</div> <div class=\"ace-line ace-line old-record-id-OlZrdWHKIoUqszxbrFwcK5zcnke\">3、最多可上传5张照片。</div> </div>
     *
     * @return $this
     */
    public function setFinanceLicensePics($financeLicensePics)
    {
        $this->container['financeLicensePics'] = $financeLicensePics;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


