<?php
/**
 * YopMerchantParticipationApplyDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 营销
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Promtion\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * YopMerchantParticipationApplyDTO Class Doc Comment
 *
 * @category Class
 * @description 银行活动报名明细信息
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class YopMerchantParticipationApplyDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'YopMerchantParticipationApplyDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'bankMarketingNo' => 'string',
        'bankMarketingName' => 'string',
        'applyStatus' => 'string',
        'signStatus' => 'string',
        'signUrl' => 'string',
        'merchantNo' => 'string',
        'merchantName' => 'string',
        'cardOpenMode' => 'string',
        'accountName' => 'string',
        'phone' => 'string',
        'address' => 'string',
        'remark' => 'string',
        'branchBank' => 'string',
        'bankCardNo' => 'string',
        'applyDate' => 'string',
        'bindCardDate' => 'string',
        'finishDate' => 'string',
        'errorMessage' => 'string',
        'applySource' => 'string',
        'applyNo' => 'string',
        'applyStatusChangeList' => '\Yeepay\Yop\Sdk\Service\Promtion\Model\YopApplyStatusChangeDTO[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'bankMarketingNo' => null,
        'bankMarketingName' => null,
        'applyStatus' => 'enum',
        'signStatus' => 'enum',
        'signUrl' => null,
        'merchantNo' => null,
        'merchantName' => null,
        'cardOpenMode' => 'enum',
        'accountName' => null,
        'phone' => null,
        'address' => null,
        'remark' => null,
        'branchBank' => null,
        'bankCardNo' => null,
        'applyDate' => null,
        'bindCardDate' => null,
        'finishDate' => null,
        'errorMessage' => null,
        'applySource' => 'enum',
        'applyNo' => null,
        'applyStatusChangeList' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bankMarketingNo' => 'bankMarketingNo',
        'bankMarketingName' => 'bankMarketingName',
        'applyStatus' => 'applyStatus',
        'signStatus' => 'signStatus',
        'signUrl' => 'signUrl',
        'merchantNo' => 'merchantNo',
        'merchantName' => 'merchantName',
        'cardOpenMode' => 'cardOpenMode',
        'accountName' => 'accountName',
        'phone' => 'phone',
        'address' => 'address',
        'remark' => 'remark',
        'branchBank' => 'branchBank',
        'bankCardNo' => 'bankCardNo',
        'applyDate' => 'applyDate',
        'bindCardDate' => 'bindCardDate',
        'finishDate' => 'finishDate',
        'errorMessage' => 'errorMessage',
        'applySource' => 'applySource',
        'applyNo' => 'applyNo',
        'applyStatusChangeList' => 'applyStatusChangeList'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bankMarketingNo' => 'setBankMarketingNo',
        'bankMarketingName' => 'setBankMarketingName',
        'applyStatus' => 'setApplyStatus',
        'signStatus' => 'setSignStatus',
        'signUrl' => 'setSignUrl',
        'merchantNo' => 'setMerchantNo',
        'merchantName' => 'setMerchantName',
        'cardOpenMode' => 'setCardOpenMode',
        'accountName' => 'setAccountName',
        'phone' => 'setPhone',
        'address' => 'setAddress',
        'remark' => 'setRemark',
        'branchBank' => 'setBranchBank',
        'bankCardNo' => 'setBankCardNo',
        'applyDate' => 'setApplyDate',
        'bindCardDate' => 'setBindCardDate',
        'finishDate' => 'setFinishDate',
        'errorMessage' => 'setErrorMessage',
        'applySource' => 'setApplySource',
        'applyNo' => 'setApplyNo',
        'applyStatusChangeList' => 'setApplyStatusChangeList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bankMarketingNo' => 'getBankMarketingNo',
        'bankMarketingName' => 'getBankMarketingName',
        'applyStatus' => 'getApplyStatus',
        'signStatus' => 'getSignStatus',
        'signUrl' => 'getSignUrl',
        'merchantNo' => 'getMerchantNo',
        'merchantName' => 'getMerchantName',
        'cardOpenMode' => 'getCardOpenMode',
        'accountName' => 'getAccountName',
        'phone' => 'getPhone',
        'address' => 'getAddress',
        'remark' => 'getRemark',
        'branchBank' => 'getBranchBank',
        'bankCardNo' => 'getBankCardNo',
        'applyDate' => 'getApplyDate',
        'bindCardDate' => 'getBindCardDate',
        'finishDate' => 'getFinishDate',
        'errorMessage' => 'getErrorMessage',
        'applySource' => 'getApplySource',
        'applyNo' => 'getApplyNo',
        'applyStatusChangeList' => 'getApplyStatusChangeList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const APPLY_STATUS_WAIT_OPEN_CARD = 'WAIT_OPEN_CARD';
    const APPLY_STATUS_WAIT_BANK_AUTH = 'WAIT_BANK_AUTH';
    const APPLY_STATUS_BANK_AUTH_FAIL = 'BANK_AUTH_FAIL';
    const APPLY_STATUS_SUCCESS = 'SUCCESS';
    const APPLY_STATUS_INTERRUPTION = 'INTERRUPTION';
    const APPLY_STATUS_EXPIRED = 'EXPIRED';
    const SIGN_STATUS_PROCESSING = 'PROCESSING';
    const SIGN_STATUS_WAIT_SIGN = 'WAIT_SIGN';
    const SIGN_STATUS_FAIL = 'FAIL';
    const SIGN_STATUS_SUCCESS = 'SUCCESS';
    const CARD_OPEN_MODE_BANK_DOORSTEP = 'BANK_DOORSTEP';
    const CARD_OPEN_MODE_OFFLINE_CABINET = 'OFFLINE_CABINET';
    const APPLY_SOURCE_YEEPAY = 'YEEPAY';
    const APPLY_SOURCE_MERCHANT = 'MERCHANT';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getApplyStatusAllowableValues()
    {
        return [
            self::APPLY_STATUS_WAIT_OPEN_CARD,
            self::APPLY_STATUS_WAIT_BANK_AUTH,
            self::APPLY_STATUS_BANK_AUTH_FAIL,
            self::APPLY_STATUS_SUCCESS,
            self::APPLY_STATUS_INTERRUPTION,
            self::APPLY_STATUS_EXPIRED,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSignStatusAllowableValues()
    {
        return [
            self::SIGN_STATUS_PROCESSING,
            self::SIGN_STATUS_WAIT_SIGN,
            self::SIGN_STATUS_FAIL,
            self::SIGN_STATUS_SUCCESS,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCardOpenModeAllowableValues()
    {
        return [
            self::CARD_OPEN_MODE_BANK_DOORSTEP,
            self::CARD_OPEN_MODE_OFFLINE_CABINET,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getApplySourceAllowableValues()
    {
        return [
            self::APPLY_SOURCE_YEEPAY,
            self::APPLY_SOURCE_MERCHANT,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['bankMarketingNo'] = isset($data['bankMarketingNo']) ? $data['bankMarketingNo'] : null;
        $this->container['bankMarketingName'] = isset($data['bankMarketingName']) ? $data['bankMarketingName'] : null;
        $this->container['applyStatus'] = isset($data['applyStatus']) ? $data['applyStatus'] : null;
        $this->container['signStatus'] = isset($data['signStatus']) ? $data['signStatus'] : null;
        $this->container['signUrl'] = isset($data['signUrl']) ? $data['signUrl'] : null;
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
        $this->container['merchantName'] = isset($data['merchantName']) ? $data['merchantName'] : null;
        $this->container['cardOpenMode'] = isset($data['cardOpenMode']) ? $data['cardOpenMode'] : null;
        $this->container['accountName'] = isset($data['accountName']) ? $data['accountName'] : null;
        $this->container['phone'] = isset($data['phone']) ? $data['phone'] : null;
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
        $this->container['remark'] = isset($data['remark']) ? $data['remark'] : null;
        $this->container['branchBank'] = isset($data['branchBank']) ? $data['branchBank'] : null;
        $this->container['bankCardNo'] = isset($data['bankCardNo']) ? $data['bankCardNo'] : null;
        $this->container['applyDate'] = isset($data['applyDate']) ? $data['applyDate'] : null;
        $this->container['bindCardDate'] = isset($data['bindCardDate']) ? $data['bindCardDate'] : null;
        $this->container['finishDate'] = isset($data['finishDate']) ? $data['finishDate'] : null;
        $this->container['errorMessage'] = isset($data['errorMessage']) ? $data['errorMessage'] : null;
        $this->container['applySource'] = isset($data['applySource']) ? $data['applySource'] : null;
        $this->container['applyNo'] = isset($data['applyNo']) ? $data['applyNo'] : null;
        $this->container['applyStatusChangeList'] = isset($data['applyStatusChangeList']) ? $data['applyStatusChangeList'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getApplyStatusAllowableValues();
        if (!is_null($this->container['applyStatus']) && !in_array($this->container['applyStatus'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'applyStatus', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSignStatusAllowableValues();
        if (!is_null($this->container['signStatus']) && !in_array($this->container['signStatus'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'signStatus', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCardOpenModeAllowableValues();
        if (!is_null($this->container['cardOpenMode']) && !in_array($this->container['cardOpenMode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'cardOpenMode', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getApplySourceAllowableValues();
        if (!is_null($this->container['applySource']) && !in_array($this->container['applySource'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'applySource', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bankMarketingNo
     *
     * @return string
     */
    public function getBankMarketingNo()
    {
        return $this->container['bankMarketingNo'];
    }

    /**
     * Sets bankMarketingNo
     *
     * @param string $bankMarketingNo bankMarketingNo
     *
     * @return $this
     */
    public function setBankMarketingNo($bankMarketingNo)
    {
        $this->container['bankMarketingNo'] = $bankMarketingNo;

        return $this;
    }

    /**
     * Gets bankMarketingName
     *
     * @return string
     */
    public function getBankMarketingName()
    {
        return $this->container['bankMarketingName'];
    }

    /**
     * Sets bankMarketingName
     *
     * @param string $bankMarketingName bankMarketingName
     *
     * @return $this
     */
    public function setBankMarketingName($bankMarketingName)
    {
        $this->container['bankMarketingName'] = $bankMarketingName;

        return $this;
    }

    /**
     * Gets applyStatus
     *
     * @return string
     */
    public function getApplyStatus()
    {
        return $this->container['applyStatus'];
    }

    /**
     * Sets applyStatus
     *
     * @param string $applyStatus 可选项如下: WAIT_OPEN_CARD:待绑卡 WAIT_BANK_AUTH:待银行审核 BANK_AUTH_FAIL:报名失败 SUCCESS:报名成功 INTERRUPTION:中断退出 EXPIRED:已失效
     *
     * @return $this
     */
    public function setApplyStatus($applyStatus)
    {
        $allowedValues = $this->getApplyStatusAllowableValues();
        if (!is_null($applyStatus) && !in_array($applyStatus, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'applyStatus', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['applyStatus'] = $applyStatus;

        return $this;
    }

    /**
     * Gets signStatus
     *
     * @return string
     */
    public function getSignStatus()
    {
        return $this->container['signStatus'];
    }

    /**
     * Sets signStatus
     *
     * @param string $signStatus 可选项如下: PROCESSING:处理中 WAIT_SIGN:待签署 FAIL:失败 SUCCESS:成功
     *
     * @return $this
     */
    public function setSignStatus($signStatus)
    {
        $allowedValues = $this->getSignStatusAllowableValues();
        if (!is_null($signStatus) && !in_array($signStatus, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'signStatus', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['signStatus'] = $signStatus;

        return $this;
    }

    /**
     * Gets signUrl
     *
     * @return string
     */
    public function getSignUrl()
    {
        return $this->container['signUrl'];
    }

    /**
     * Sets signUrl
     *
     * @param string $signUrl signUrl
     *
     * @return $this
     */
    public function setSignUrl($signUrl)
    {
        $this->container['signUrl'] = $signUrl;

        return $this;
    }

    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo merchantNo
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }

    /**
     * Gets merchantName
     *
     * @return string
     */
    public function getMerchantName()
    {
        return $this->container['merchantName'];
    }

    /**
     * Sets merchantName
     *
     * @param string $merchantName merchantName
     *
     * @return $this
     */
    public function setMerchantName($merchantName)
    {
        $this->container['merchantName'] = $merchantName;

        return $this;
    }

    /**
     * Gets cardOpenMode
     *
     * @return string
     */
    public function getCardOpenMode()
    {
        return $this->container['cardOpenMode'];
    }

    /**
     * Sets cardOpenMode
     *
     * @param string $cardOpenMode 可选项如下: BANK_DOORSTEP:银行上门 OFFLINE_CABINET:线下临柜
     *
     * @return $this
     */
    public function setCardOpenMode($cardOpenMode)
    {
        $allowedValues = $this->getCardOpenModeAllowableValues();
        if (!is_null($cardOpenMode) && !in_array($cardOpenMode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'cardOpenMode', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['cardOpenMode'] = $cardOpenMode;

        return $this;
    }

    /**
     * Gets accountName
     *
     * @return string
     */
    public function getAccountName()
    {
        return $this->container['accountName'];
    }

    /**
     * Sets accountName
     *
     * @param string $accountName accountName
     *
     * @return $this
     */
    public function setAccountName($accountName)
    {
        $this->container['accountName'] = $accountName;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone phone
     *
     * @return $this
     */
    public function setPhone($phone)
    {
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string $address address
     *
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets remark
     *
     * @return string
     */
    public function getRemark()
    {
        return $this->container['remark'];
    }

    /**
     * Sets remark
     *
     * @param string $remark remark
     *
     * @return $this
     */
    public function setRemark($remark)
    {
        $this->container['remark'] = $remark;

        return $this;
    }

    /**
     * Gets branchBank
     *
     * @return string
     */
    public function getBranchBank()
    {
        return $this->container['branchBank'];
    }

    /**
     * Sets branchBank
     *
     * @param string $branchBank branchBank
     *
     * @return $this
     */
    public function setBranchBank($branchBank)
    {
        $this->container['branchBank'] = $branchBank;

        return $this;
    }

    /**
     * Gets bankCardNo
     *
     * @return string
     */
    public function getBankCardNo()
    {
        return $this->container['bankCardNo'];
    }

    /**
     * Sets bankCardNo
     *
     * @param string $bankCardNo <p>前6后4脱敏</p>
     *
     * @return $this
     */
    public function setBankCardNo($bankCardNo)
    {
        $this->container['bankCardNo'] = $bankCardNo;

        return $this;
    }

    /**
     * Gets applyDate
     *
     * @return string
     */
    public function getApplyDate()
    {
        return $this->container['applyDate'];
    }

    /**
     * Sets applyDate
     *
     * @param string $applyDate applyDate
     *
     * @return $this
     */
    public function setApplyDate($applyDate)
    {
        $this->container['applyDate'] = $applyDate;

        return $this;
    }

    /**
     * Gets bindCardDate
     *
     * @return string
     */
    public function getBindCardDate()
    {
        return $this->container['bindCardDate'];
    }

    /**
     * Sets bindCardDate
     *
     * @param string $bindCardDate bindCardDate
     *
     * @return $this
     */
    public function setBindCardDate($bindCardDate)
    {
        $this->container['bindCardDate'] = $bindCardDate;

        return $this;
    }

    /**
     * Gets finishDate
     *
     * @return string
     */
    public function getFinishDate()
    {
        return $this->container['finishDate'];
    }

    /**
     * Sets finishDate
     *
     * @param string $finishDate finishDate
     *
     * @return $this
     */
    public function setFinishDate($finishDate)
    {
        $this->container['finishDate'] = $finishDate;

        return $this;
    }

    /**
     * Gets errorMessage
     *
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->container['errorMessage'];
    }

    /**
     * Sets errorMessage
     *
     * @param string $errorMessage errorMessage
     *
     * @return $this
     */
    public function setErrorMessage($errorMessage)
    {
        $this->container['errorMessage'] = $errorMessage;

        return $this;
    }

    /**
     * Gets applySource
     *
     * @return string
     */
    public function getApplySource()
    {
        return $this->container['applySource'];
    }

    /**
     * Sets applySource
     *
     * @param string $applySource <p>如是易宝运营通过易宝内部运营工具完成报名，则申请来源为运营报名。如是商户通过接口/商户后台发起报名，则申请来源为商户报名。</p> 可选项如下: YEEPAY:运营报名 MERCHANT:商户报名
     *
     * @return $this
     */
    public function setApplySource($applySource)
    {
        $allowedValues = $this->getApplySourceAllowableValues();
        if (!is_null($applySource) && !in_array($applySource, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'applySource', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['applySource'] = $applySource;

        return $this;
    }

    /**
     * Gets applyNo
     *
     * @return string
     */
    public function getApplyNo()
    {
        return $this->container['applyNo'];
    }

    /**
     * Sets applyNo
     *
     * @param string $applyNo <p>子商户报名时生成的报名申请ID</p>
     *
     * @return $this
     */
    public function setApplyNo($applyNo)
    {
        $this->container['applyNo'] = $applyNo;

        return $this;
    }

    /**
     * Gets applyStatusChangeList
     *
     * @return \Yeepay\Yop\Sdk\Service\Promtion\Model\YopApplyStatusChangeDTO[]
     */
    public function getApplyStatusChangeList()
    {
        return $this->container['applyStatusChangeList'];
    }

    /**
     * Sets applyStatusChangeList
     *
     * @param \Yeepay\Yop\Sdk\Service\Promtion\Model\YopApplyStatusChangeDTO[] $applyStatusChangeList applyStatusChangeList
     *
     * @return $this
     */
    public function setApplyStatusChangeList($applyStatusChangeList)
    {
        $this->container['applyStatusChangeList'] = $applyStatusChangeList;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


