<?php
/**
 * QueryNetInProgressRespDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 子商户管理
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Mer\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * QueryNetInProgressRespDto Class Doc Comment
 *
 * @category Class
 * @description 查询H5入网进度返回
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QueryNetInProgressRespDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'QueryNetInProgressRespDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'code' => 'string',
        'msg' => 'string',
        'requestNo' => 'string',
        'applicationStatus' => 'string',
        'applicationNo' => 'string',
        'merchantNo' => 'string',
        'auditOpinion' => 'string',
        'progressDescription' => 'string',
        'intentionAuthUrl' => 'string',
        'elecSignUrl' => 'string',
        'netInUrl' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'code' => null,
        'msg' => null,
        'requestNo' => null,
        'applicationStatus' => null,
        'applicationNo' => null,
        'merchantNo' => null,
        'auditOpinion' => null,
        'progressDescription' => null,
        'intentionAuthUrl' => null,
        'elecSignUrl' => null,
        'netInUrl' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'msg' => 'msg',
        'requestNo' => 'requestNo',
        'applicationStatus' => 'applicationStatus',
        'applicationNo' => 'applicationNo',
        'merchantNo' => 'merchantNo',
        'auditOpinion' => 'auditOpinion',
        'progressDescription' => 'progressDescription',
        'intentionAuthUrl' => 'intentionAuthUrl',
        'elecSignUrl' => 'elecSignUrl',
        'netInUrl' => 'netInUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'msg' => 'setMsg',
        'requestNo' => 'setRequestNo',
        'applicationStatus' => 'setApplicationStatus',
        'applicationNo' => 'setApplicationNo',
        'merchantNo' => 'setMerchantNo',
        'auditOpinion' => 'setAuditOpinion',
        'progressDescription' => 'setProgressDescription',
        'intentionAuthUrl' => 'setIntentionAuthUrl',
        'elecSignUrl' => 'setElecSignUrl',
        'netInUrl' => 'setNetInUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'msg' => 'getMsg',
        'requestNo' => 'getRequestNo',
        'applicationStatus' => 'getApplicationStatus',
        'applicationNo' => 'getApplicationNo',
        'merchantNo' => 'getMerchantNo',
        'auditOpinion' => 'getAuditOpinion',
        'progressDescription' => 'getProgressDescription',
        'intentionAuthUrl' => 'getIntentionAuthUrl',
        'elecSignUrl' => 'getElecSignUrl',
        'netInUrl' => 'getNetInUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['code'] = isset($data['code']) ? $data['code'] : null;
        $this->container['msg'] = isset($data['msg']) ? $data['msg'] : null;
        $this->container['requestNo'] = isset($data['requestNo']) ? $data['requestNo'] : null;
        $this->container['applicationStatus'] = isset($data['applicationStatus']) ? $data['applicationStatus'] : null;
        $this->container['applicationNo'] = isset($data['applicationNo']) ? $data['applicationNo'] : null;
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
        $this->container['auditOpinion'] = isset($data['auditOpinion']) ? $data['auditOpinion'] : null;
        $this->container['progressDescription'] = isset($data['progressDescription']) ? $data['progressDescription'] : null;
        $this->container['intentionAuthUrl'] = isset($data['intentionAuthUrl']) ? $data['intentionAuthUrl'] : null;
        $this->container['elecSignUrl'] = isset($data['elecSignUrl']) ? $data['elecSignUrl'] : null;
        $this->container['netInUrl'] = isset($data['netInUrl']) ? $data['netInUrl'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        if ($this->container['msg'] === null) {
            $invalidProperties[] = "'msg' can't be null";
        }
        if ($this->container['applicationStatus'] === null) {
            $invalidProperties[] = "'applicationStatus' can't be null";
        }
        if ($this->container['netInUrl'] === null) {
            $invalidProperties[] = "'netInUrl' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code code
     *
     * @return $this
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets msg
     *
     * @return string
     */
    public function getMsg()
    {
        return $this->container['msg'];
    }

    /**
     * Sets msg
     *
     * @param string $msg <p>当code！=MAS000000,返回具体失败原因</p>
     *
     * @return $this
     */
    public function setMsg($msg)
    {
        $this->container['msg'] = $msg;

        return $this;
    }

    /**
     * Gets requestNo
     *
     * @return string
     */
    public function getRequestNo()
    {
        return $this->container['requestNo'];
    }

    /**
     * Sets requestNo
     *
     * @param string $requestNo requestNo
     *
     * @return $this
     */
    public function setRequestNo($requestNo)
    {
        $this->container['requestNo'] = $requestNo;

        return $this;
    }

    /**
     * Gets applicationStatus
     *
     * @return string
     */
    public function getApplicationStatus()
    {
        return $this->container['applicationStatus'];
    }

    /**
     * Sets applicationStatus
     *
     * @param string $applicationStatus <div data-page-id=\"ThBzde76xoUmVhxQNPGcYPQJnYZ\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-Ggp6d69eDo1BDExKzgucLTltndd\">WAIT_SIGN：编辑中</div> <div class=\"ace-line ace-line old-record-id-S7F8dgihdoAFIhxPdGScryZMn6c\">REVIEWING:申请审核中</div> <div class=\"ace-line ace-line old-record-id-L3iYddl8co87kJxzTxZcN7b8n93\">REVIEW_BACK:申请已驳回</div> <div class=\"ace-line ace-line old-record-id-KI7OdUNcFodjXRxsHkycpOgCn2K\">AUTHENTICITY_VERIFYING:真实性验证中</div> <div class=\"ace-line ace-line old-record-id-NSBIdnWV1otWVqx4WrDcn78TnXc\">AGREEMENT_SIGNING:协议待签署</div> <div class=\"ace-line ace-line old-record-id-URjrdRBWioZzfIxfhJVcYT9onrf\">BUSINESS_OPENING:业务开通中</div> <div class=\"ace-line ace-line old-record-id-F6rKddGt6o5HItxrWK2cKTeOnff\">COMPLETED:申请已完成</div> </div>
     *
     * @return $this
     */
    public function setApplicationStatus($applicationStatus)
    {
        $this->container['applicationStatus'] = $applicationStatus;

        return $this;
    }

    /**
     * Gets applicationNo
     *
     * @return string
     */
    public function getApplicationNo()
    {
        return $this->container['applicationNo'];
    }

    /**
     * Sets applicationNo
     *
     * @param string $applicationNo <div class=\"width-50-perc ivu-form-item\" data-v-69445fd2=\"\"> <div class=\"ivu-form-item-content\"> <div data-page-id=\"ThBzde76xoUmVhxQNPGcYPQJnYZ\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-IunQdSjbpoJgaaxIHFQcH5oKnkf\">生成入网单成功后返回</div> </div> </div> </div>
     *
     * @return $this
     */
    public function setApplicationNo($applicationNo)
    {
        $this->container['applicationNo'] = $applicationNo;

        return $this;
    }

    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo <div data-page-id=\"ThBzde76xoUmVhxQNPGcYPQJnYZ\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-H5COdOBJJoWRLYxT1SQcnJ34nCf\">商编生成后返回</div> </div>
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }

    /**
     * Gets auditOpinion
     *
     * @return string
     */
    public function getAuditOpinion()
    {
        return $this->container['auditOpinion'];
    }

    /**
     * Sets auditOpinion
     *
     * @param string $auditOpinion <p>&ldquo;申请已驳回&rdquo;或者&ldquo;业务开通中&rdquo;或者&ldquo;申请已完成&rdquo;时，回传的原因<br />1.\"申请已驳回\"时返回驳回原因；<br />2.\"业务开通中\"时，如果报备失败返回原因；<br />3.\"申请已完成\"时，如果存在资质缺失，返回资质缺失说明；</p>
     *
     * @return $this
     */
    public function setAuditOpinion($auditOpinion)
    {
        $this->container['auditOpinion'] = $auditOpinion;

        return $this;
    }

    /**
     * Gets progressDescription
     *
     * @return string
     */
    public function getProgressDescription()
    {
        return $this->container['progressDescription'];
    }

    /**
     * Sets progressDescription
     *
     * @param string $progressDescription <div class=\"params-content\" data-v-07c52057=\"\">当申请状态为&ldquo;真实性验证中&rdquo;时返回，其中\"REMIT_AUTH\" 代表&ldquo;待意愿认证&rdquo;</div>
     *
     * @return $this
     */
    public function setProgressDescription($progressDescription)
    {
        $this->container['progressDescription'] = $progressDescription;

        return $this;
    }

    /**
     * Gets intentionAuthUrl
     *
     * @return string
     */
    public function getIntentionAuthUrl()
    {
        return $this->container['intentionAuthUrl'];
    }

    /**
     * Sets intentionAuthUrl
     *
     * @param string $intentionAuthUrl <div class=\"width-50-perc ivu-form-item\" data-v-69445fd2=\"\"> <div class=\"ivu-form-item-content\"> <p data-v-69445fd2=\"\">当进度说明中返回有REMIT_AUTH时返回链接</p> </div> </div>
     *
     * @return $this
     */
    public function setIntentionAuthUrl($intentionAuthUrl)
    {
        $this->container['intentionAuthUrl'] = $intentionAuthUrl;

        return $this;
    }

    /**
     * Gets elecSignUrl
     *
     * @return string
     */
    public function getElecSignUrl()
    {
        return $this->container['elecSignUrl'];
    }

    /**
     * Sets elecSignUrl
     *
     * @param string $elecSignUrl elecSignUrl
     *
     * @return $this
     */
    public function setElecSignUrl($elecSignUrl)
    {
        $this->container['elecSignUrl'] = $elecSignUrl;

        return $this;
    }

    /**
     * Gets netInUrl
     *
     * @return string
     */
    public function getNetInUrl()
    {
        return $this->container['netInUrl'];
    }

    /**
     * Sets netInUrl
     *
     * @param string $netInUrl <p>H5入网链接地址</p>
     *
     * @return $this
     */
    public function setNetInUrl($netInUrl)
    {
        $this->container['netInUrl'] = $netInUrl;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


