<?php
/**
 * UserApplyReqDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 子商户管理
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Mer\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * UserApplyReqDTO Class Doc Comment
 *
 * @category Class
 * @description 申请开通用户记账簿请求参数
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApplyReqDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UserApplyReqDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'bankInfo' => '\Yeepay\Yop\Sdk\Service\Mer\Model\UserBankAccountDTO',
        'bookExtInfo' => '\Yeepay\Yop\Sdk\Service\Mer\Model\UserBookExtInfoDTO',
        'contactInfo' => '\Yeepay\Yop\Sdk\Service\Mer\Model\UserContactDTO',
        'legalInfo' => '\Yeepay\Yop\Sdk\Service\Mer\Model\UserLegalDTO',
        'businessTypeList' => 'string[]',
        'signType' => 'string',
        'notifyUrl' => 'string',
        'requestNo' => 'string',
        'subjectInfo' => '\Yeepay\Yop\Sdk\Service\Mer\Model\UserSubjectDto',
        'merchantNo' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'bankInfo' => null,
        'bookExtInfo' => null,
        'contactInfo' => null,
        'legalInfo' => null,
        'businessTypeList' => 'string',
        'signType' => null,
        'notifyUrl' => 'notify-url',
        'requestNo' => null,
        'subjectInfo' => null,
        'merchantNo' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bankInfo' => 'bankInfo',
        'bookExtInfo' => 'bookExtInfo',
        'contactInfo' => 'contactInfo',
        'legalInfo' => 'legalInfo',
        'businessTypeList' => 'businessTypeList',
        'signType' => 'signType',
        'notifyUrl' => 'notifyUrl',
        'requestNo' => 'requestNo',
        'subjectInfo' => 'subjectInfo',
        'merchantNo' => 'merchantNo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bankInfo' => 'setBankInfo',
        'bookExtInfo' => 'setBookExtInfo',
        'contactInfo' => 'setContactInfo',
        'legalInfo' => 'setLegalInfo',
        'businessTypeList' => 'setBusinessTypeList',
        'signType' => 'setSignType',
        'notifyUrl' => 'setNotifyUrl',
        'requestNo' => 'setRequestNo',
        'subjectInfo' => 'setSubjectInfo',
        'merchantNo' => 'setMerchantNo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bankInfo' => 'getBankInfo',
        'bookExtInfo' => 'getBookExtInfo',
        'contactInfo' => 'getContactInfo',
        'legalInfo' => 'getLegalInfo',
        'businessTypeList' => 'getBusinessTypeList',
        'signType' => 'getSignType',
        'notifyUrl' => 'getNotifyUrl',
        'requestNo' => 'getRequestNo',
        'subjectInfo' => 'getSubjectInfo',
        'merchantNo' => 'getMerchantNo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const SIGN_TYPE_PERSON = 'PERSON';
    const SIGN_TYPE_ENTERPRISE = 'ENTERPRISE';
    const SIGN_TYPE_INDIVIDUAL = 'INDIVIDUAL';
    const SIGN_TYPE_INSTITUTION = 'INSTITUTION';
    const SIGN_TYPE_COMMUNITY = 'COMMUNITY';
    const SIGN_TYPE_PEOPLE_RUN_NON_ENTERPRISE = 'PEOPLE_RUN_NON_ENTERPRISE';
    const SIGN_TYPE_ABROAD_ENTERPRISE = 'ABROAD_ENTERPRISE';
    const SIGN_TYPE_ABROAD_PAYMENT_INSTITUTION = 'ABROAD_PAYMENT_INSTITUTION';
    const SIGN_TYPE_ABROAD_PERSON = 'ABROAD_PERSON';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSignTypeAllowableValues()
    {
        return [
            self::SIGN_TYPE_PERSON,
            self::SIGN_TYPE_ENTERPRISE,
            self::SIGN_TYPE_INDIVIDUAL,
            self::SIGN_TYPE_INSTITUTION,
            self::SIGN_TYPE_COMMUNITY,
            self::SIGN_TYPE_PEOPLE_RUN_NON_ENTERPRISE,
            self::SIGN_TYPE_ABROAD_ENTERPRISE,
            self::SIGN_TYPE_ABROAD_PAYMENT_INSTITUTION,
            self::SIGN_TYPE_ABROAD_PERSON,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['bankInfo'] = isset($data['bankInfo']) ? $data['bankInfo'] : null;
        $this->container['bookExtInfo'] = isset($data['bookExtInfo']) ? $data['bookExtInfo'] : null;
        $this->container['contactInfo'] = isset($data['contactInfo']) ? $data['contactInfo'] : null;
        $this->container['legalInfo'] = isset($data['legalInfo']) ? $data['legalInfo'] : null;
        $this->container['businessTypeList'] = isset($data['businessTypeList']) ? $data['businessTypeList'] : null;
        $this->container['signType'] = isset($data['signType']) ? $data['signType'] : null;
        $this->container['notifyUrl'] = isset($data['notifyUrl']) ? $data['notifyUrl'] : null;
        $this->container['requestNo'] = isset($data['requestNo']) ? $data['requestNo'] : null;
        $this->container['subjectInfo'] = isset($data['subjectInfo']) ? $data['subjectInfo'] : null;
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['bankInfo'] === null) {
            $invalidProperties[] = "'bankInfo' can't be null";
        }
        if ($this->container['legalInfo'] === null) {
            $invalidProperties[] = "'legalInfo' can't be null";
        }
        if ($this->container['businessTypeList'] === null) {
            $invalidProperties[] = "'businessTypeList' can't be null";
        }
        if ($this->container['signType'] === null) {
            $invalidProperties[] = "'signType' can't be null";
        }
        $allowedValues = $this->getSignTypeAllowableValues();
        if (!is_null($this->container['signType']) && !in_array($this->container['signType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'signType', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['notifyUrl'] === null) {
            $invalidProperties[] = "'notifyUrl' can't be null";
        }
        if ($this->container['requestNo'] === null) {
            $invalidProperties[] = "'requestNo' can't be null";
        }
        if ($this->container['merchantNo'] === null) {
            $invalidProperties[] = "'merchantNo' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bankInfo
     *
     * @return \Yeepay\Yop\Sdk\Service\Mer\Model\UserBankAccountDTO
     */
    public function getBankInfo()
    {
        return $this->container['bankInfo'];
    }

    /**
     * Sets bankInfo
     *
     * @param \Yeepay\Yop\Sdk\Service\Mer\Model\UserBankAccountDTO $bankInfo bankInfo
     *
     * @return $this
     */
    public function setBankInfo($bankInfo)
    {
        $this->container['bankInfo'] = $bankInfo;

        return $this;
    }

    /**
     * Gets bookExtInfo
     *
     * @return \Yeepay\Yop\Sdk\Service\Mer\Model\UserBookExtInfoDTO
     */
    public function getBookExtInfo()
    {
        return $this->container['bookExtInfo'];
    }

    /**
     * Sets bookExtInfo
     *
     * @param \Yeepay\Yop\Sdk\Service\Mer\Model\UserBookExtInfoDTO $bookExtInfo bookExtInfo
     *
     * @return $this
     */
    public function setBookExtInfo($bookExtInfo)
    {
        $this->container['bookExtInfo'] = $bookExtInfo;

        return $this;
    }

    /**
     * Gets contactInfo
     *
     * @return \Yeepay\Yop\Sdk\Service\Mer\Model\UserContactDTO
     */
    public function getContactInfo()
    {
        return $this->container['contactInfo'];
    }

    /**
     * Sets contactInfo
     *
     * @param \Yeepay\Yop\Sdk\Service\Mer\Model\UserContactDTO $contactInfo contactInfo
     *
     * @return $this
     */
    public function setContactInfo($contactInfo)
    {
        $this->container['contactInfo'] = $contactInfo;

        return $this;
    }

    /**
     * Gets legalInfo
     *
     * @return \Yeepay\Yop\Sdk\Service\Mer\Model\UserLegalDTO
     */
    public function getLegalInfo()
    {
        return $this->container['legalInfo'];
    }

    /**
     * Sets legalInfo
     *
     * @param \Yeepay\Yop\Sdk\Service\Mer\Model\UserLegalDTO $legalInfo legalInfo
     *
     * @return $this
     */
    public function setLegalInfo($legalInfo)
    {
        $this->container['legalInfo'] = $legalInfo;

        return $this;
    }

    /**
     * Gets businessTypeList
     *
     * @return string[]
     */
    public function getBusinessTypeList()
    {
        return $this->container['businessTypeList'];
    }

    /**
     * Sets businessTypeList
     *
     * @param string[] $businessTypeList <div data-page-id=\"R89UdQrldouzcAxzrVzcp7wLnLg\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-Raw7dTrjPozTrixw49Oc5rK0n1e\">ACCOUNT_BOOK：记账簿（目前仅支持记账簿）</div> </div>
     *
     * @return $this
     */
    public function setBusinessTypeList($businessTypeList)
    {
        $this->container['businessTypeList'] = $businessTypeList;

        return $this;
    }

    /**
     * Gets signType
     *
     * @return string
     */
    public function getSignType()
    {
        return $this->container['signType'];
    }

    /**
     * Sets signType
     *
     * @param string $signType <p>商户签约类型，枚举值如下：<br />1、INDIVIDUAL:个体工商户<br />2、ENTERPRISE:企业<br />3、INSTITUTION:事业单位<br />4、COMMUNITY:社会团体<br />5、PEOPLE_RUN_NON_ENTERPRISE:民办非企业<br />6、PERSON：个人<br />*说明:<br />1、个体工商户：一般为个体户、个体工商户、个体经营。<br />2、企业：一般为有限公司、有限责任公司<br />3、事业单位：包括国内各级、各类政府机构、事业单位等（如：公安、党 团、司法、交通、旅游、工商税务、市政、医疗、教育、学校等机构）<br />4、社会团体：非营利性社会组织<br />5、民办非企业</p>
     *
     * @return $this
     */
    public function setSignType($signType)
    {
        $allowedValues = $this->getSignTypeAllowableValues();
        if (!in_array($signType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'signType', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['signType'] = $signType;

        return $this;
    }

    /**
     * Gets notifyUrl
     *
     * @return string
     */
    public function getNotifyUrl()
    {
        return $this->container['notifyUrl'];
    }

    /**
     * Sets notifyUrl
     *
     * @param string $notifyUrl <p>用于接受电签签署以及申请完成的回调通知</p>
     *
     * @return $this
     */
    public function setNotifyUrl($notifyUrl)
    {
        $this->container['notifyUrl'] = $notifyUrl;

        return $this;
    }

    /**
     * Gets requestNo
     *
     * @return string
     */
    public function getRequestNo()
    {
        return $this->container['requestNo'];
    }

    /**
     * Sets requestNo
     *
     * @param string $requestNo <p>请求号</p>
     *
     * @return $this
     */
    public function setRequestNo($requestNo)
    {
        $this->container['requestNo'] = $requestNo;

        return $this;
    }

    /**
     * Gets subjectInfo
     *
     * @return \Yeepay\Yop\Sdk\Service\Mer\Model\UserSubjectDto
     */
    public function getSubjectInfo()
    {
        return $this->container['subjectInfo'];
    }

    /**
     * Sets subjectInfo
     *
     * @param \Yeepay\Yop\Sdk\Service\Mer\Model\UserSubjectDto $subjectInfo subjectInfo
     *
     * @return $this
     */
    public function setSubjectInfo($subjectInfo)
    {
        $this->container['subjectInfo'] = $subjectInfo;

        return $this;
    }

    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo <div data-page-id=\"R89UdQrldouzcAxzrVzcp7wLnLg\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-QjQudxk0OoQym8xajpOc4Fpondd\">用户归属商编</div> </div>
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


