<?php
/**
 * YopQueryDivideBackResDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 分账
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Divide\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * YopQueryDivideBackResDTO Class Doc Comment
 *
 * @category Class
 * @description 响应结果
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class YopQueryDivideBackResDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'YopQueryDivideBackResDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'code' => 'string',
        'message' => 'string',
        'bizSystemNo' => 'string',
        'parentMerchantNo' => 'string',
        'merchantNo' => 'string',
        'orderId' => 'string',
        'uniqueOrderNo' => 'string',
        'divideRequestId' => 'string',
        'divideBackRequestId' => 'string',
        'uniqueDivideBackNo' => 'string',
        'divideBackDetail' => 'string',
        'status' => 'string',
        'createDate' => 'string',
        'errorMessage' => 'string',
        'divideBackAccountDetail' => 'string',
        'divideBackSuccessDate' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'code' => null,
        'message' => null,
        'bizSystemNo' => null,
        'parentMerchantNo' => null,
        'merchantNo' => null,
        'orderId' => null,
        'uniqueOrderNo' => null,
        'divideRequestId' => null,
        'divideBackRequestId' => null,
        'uniqueDivideBackNo' => null,
        'divideBackDetail' => null,
        'status' => null,
        'createDate' => null,
        'errorMessage' => null,
        'divideBackAccountDetail' => null,
        'divideBackSuccessDate' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'message' => 'message',
        'bizSystemNo' => 'bizSystemNo',
        'parentMerchantNo' => 'parentMerchantNo',
        'merchantNo' => 'merchantNo',
        'orderId' => 'orderId',
        'uniqueOrderNo' => 'uniqueOrderNo',
        'divideRequestId' => 'divideRequestId',
        'divideBackRequestId' => 'divideBackRequestId',
        'uniqueDivideBackNo' => 'uniqueDivideBackNo',
        'divideBackDetail' => 'divideBackDetail',
        'status' => 'status',
        'createDate' => 'createDate',
        'errorMessage' => 'errorMessage',
        'divideBackAccountDetail' => 'divideBackAccountDetail',
        'divideBackSuccessDate' => 'divideBackSuccessDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'message' => 'setMessage',
        'bizSystemNo' => 'setBizSystemNo',
        'parentMerchantNo' => 'setParentMerchantNo',
        'merchantNo' => 'setMerchantNo',
        'orderId' => 'setOrderId',
        'uniqueOrderNo' => 'setUniqueOrderNo',
        'divideRequestId' => 'setDivideRequestId',
        'divideBackRequestId' => 'setDivideBackRequestId',
        'uniqueDivideBackNo' => 'setUniqueDivideBackNo',
        'divideBackDetail' => 'setDivideBackDetail',
        'status' => 'setStatus',
        'createDate' => 'setCreateDate',
        'errorMessage' => 'setErrorMessage',
        'divideBackAccountDetail' => 'setDivideBackAccountDetail',
        'divideBackSuccessDate' => 'setDivideBackSuccessDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'message' => 'getMessage',
        'bizSystemNo' => 'getBizSystemNo',
        'parentMerchantNo' => 'getParentMerchantNo',
        'merchantNo' => 'getMerchantNo',
        'orderId' => 'getOrderId',
        'uniqueOrderNo' => 'getUniqueOrderNo',
        'divideRequestId' => 'getDivideRequestId',
        'divideBackRequestId' => 'getDivideBackRequestId',
        'uniqueDivideBackNo' => 'getUniqueDivideBackNo',
        'divideBackDetail' => 'getDivideBackDetail',
        'status' => 'getStatus',
        'createDate' => 'getCreateDate',
        'errorMessage' => 'getErrorMessage',
        'divideBackAccountDetail' => 'getDivideBackAccountDetail',
        'divideBackSuccessDate' => 'getDivideBackSuccessDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['code'] = isset($data['code']) ? $data['code'] : null;
        $this->container['message'] = isset($data['message']) ? $data['message'] : null;
        $this->container['bizSystemNo'] = isset($data['bizSystemNo']) ? $data['bizSystemNo'] : null;
        $this->container['parentMerchantNo'] = isset($data['parentMerchantNo']) ? $data['parentMerchantNo'] : null;
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
        $this->container['orderId'] = isset($data['orderId']) ? $data['orderId'] : null;
        $this->container['uniqueOrderNo'] = isset($data['uniqueOrderNo']) ? $data['uniqueOrderNo'] : null;
        $this->container['divideRequestId'] = isset($data['divideRequestId']) ? $data['divideRequestId'] : null;
        $this->container['divideBackRequestId'] = isset($data['divideBackRequestId']) ? $data['divideBackRequestId'] : null;
        $this->container['uniqueDivideBackNo'] = isset($data['uniqueDivideBackNo']) ? $data['uniqueDivideBackNo'] : null;
        $this->container['divideBackDetail'] = isset($data['divideBackDetail']) ? $data['divideBackDetail'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['createDate'] = isset($data['createDate']) ? $data['createDate'] : null;
        $this->container['errorMessage'] = isset($data['errorMessage']) ? $data['errorMessage'] : null;
        $this->container['divideBackAccountDetail'] = isset($data['divideBackAccountDetail']) ? $data['divideBackAccountDetail'] : null;
        $this->container['divideBackSuccessDate'] = isset($data['divideBackSuccessDate']) ? $data['divideBackSuccessDate'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code <p>返回码,OPR00000 成功</p>
     *
     * @return $this
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string $message <p>返回信息描述</p>
     *
     * @return $this
     */
    public function setMessage($message)
    {
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets bizSystemNo
     *
     * @return string
     */
    public function getBizSystemNo()
    {
        return $this->container['bizSystemNo'];
    }

    /**
     * Sets bizSystemNo
     *
     * @param string $bizSystemNo <p>业务方标识</p>
     *
     * @return $this
     */
    public function setBizSystemNo($bizSystemNo)
    {
        $this->container['bizSystemNo'] = $bizSystemNo;

        return $this;
    }

    /**
     * Gets parentMerchantNo
     *
     * @return string
     */
    public function getParentMerchantNo()
    {
        return $this->container['parentMerchantNo'];
    }

    /**
     * Sets parentMerchantNo
     *
     * @param string $parentMerchantNo <p>发起方商编</p>
     *
     * @return $this
     */
    public function setParentMerchantNo($parentMerchantNo)
    {
        $this->container['parentMerchantNo'] = $parentMerchantNo;

        return $this;
    }

    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo <p>商户编号</p>
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }

    /**
     * Gets orderId
     *
     * @return string
     */
    public function getOrderId()
    {
        return $this->container['orderId'];
    }

    /**
     * Sets orderId
     *
     * @param string $orderId <p>商户收款请求号</p>
     *
     * @return $this
     */
    public function setOrderId($orderId)
    {
        $this->container['orderId'] = $orderId;

        return $this;
    }

    /**
     * Gets uniqueOrderNo
     *
     * @return string
     */
    public function getUniqueOrderNo()
    {
        return $this->container['uniqueOrderNo'];
    }

    /**
     * Sets uniqueOrderNo
     *
     * @param string $uniqueOrderNo <p>易宝收款订单号</p>
     *
     * @return $this
     */
    public function setUniqueOrderNo($uniqueOrderNo)
    {
        $this->container['uniqueOrderNo'] = $uniqueOrderNo;

        return $this;
    }

    /**
     * Gets divideRequestId
     *
     * @return string
     */
    public function getDivideRequestId()
    {
        return $this->container['divideRequestId'];
    }

    /**
     * Sets divideRequestId
     *
     * @param string $divideRequestId <p>商户分账请求号</p>
     *
     * @return $this
     */
    public function setDivideRequestId($divideRequestId)
    {
        $this->container['divideRequestId'] = $divideRequestId;

        return $this;
    }

    /**
     * Gets divideBackRequestId
     *
     * @return string
     */
    public function getDivideBackRequestId()
    {
        return $this->container['divideBackRequestId'];
    }

    /**
     * Sets divideBackRequestId
     *
     * @param string $divideBackRequestId <p>商户分账资金归还请求号</p>
     *
     * @return $this
     */
    public function setDivideBackRequestId($divideBackRequestId)
    {
        $this->container['divideBackRequestId'] = $divideBackRequestId;

        return $this;
    }

    /**
     * Gets uniqueDivideBackNo
     *
     * @return string
     */
    public function getUniqueDivideBackNo()
    {
        return $this->container['uniqueDivideBackNo'];
    }

    /**
     * Sets uniqueDivideBackNo
     *
     * @param string $uniqueDivideBackNo <p>易宝分账资金归还订单号</p>
     *
     * @return $this
     */
    public function setUniqueDivideBackNo($uniqueDivideBackNo)
    {
        $this->container['uniqueDivideBackNo'] = $uniqueDivideBackNo;

        return $this;
    }

    /**
     * Gets divideBackDetail
     *
     * @return string
     */
    public function getDivideBackDetail()
    {
        return $this->container['divideBackDetail'];
    }

    /**
     * Sets divideBackDetail
     *
     * @param string $divideBackDetail <p>分账资金归还详情</p>
     *
     * @return $this
     */
    public function setDivideBackDetail($divideBackDetail)
    {
        $this->container['divideBackDetail'] = $divideBackDetail;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status <p>PROCESSING 处理中<br />SUCCESS 归还成功<br />FAIL 归还失败</p>
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets createDate
     *
     * @return string
     */
    public function getCreateDate()
    {
        return $this->container['createDate'];
    }

    /**
     * Sets createDate
     *
     * @param string $createDate <p>分账申请时间</p>
     *
     * @return $this
     */
    public function setCreateDate($createDate)
    {
        $this->container['createDate'] = $createDate;

        return $this;
    }

    /**
     * Gets errorMessage
     *
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->container['errorMessage'];
    }

    /**
     * Sets errorMessage
     *
     * @param string $errorMessage <p>分账退回失败原因</p>
     *
     * @return $this
     */
    public function setErrorMessage($errorMessage)
    {
        $this->container['errorMessage'] = $errorMessage;

        return $this;
    }

    /**
     * Gets divideBackAccountDetail
     *
     * @return string
     */
    public function getDivideBackAccountDetail()
    {
        return $this->container['divideBackAccountDetail'];
    }

    /**
     * Sets divideBackAccountDetail
     *
     * @param string $divideBackAccountDetail <p>分账退回资金来源详情 JSON字符传 debitAmount：扣账金额 accountType：扣账账户类型 ledgerNo：分账接收方 扣账资金来源枚举值： FUND_ACCOUNT：资金账户 &nbsp;SETTLE_ACCOUNT：待结算账户</p>
     *
     * @return $this
     */
    public function setDivideBackAccountDetail($divideBackAccountDetail)
    {
        $this->container['divideBackAccountDetail'] = $divideBackAccountDetail;

        return $this;
    }

    /**
     * Gets divideBackSuccessDate
     *
     * @return string
     */
    public function getDivideBackSuccessDate()
    {
        return $this->container['divideBackSuccessDate'];
    }

    /**
     * Sets divideBackSuccessDate
     *
     * @param string $divideBackSuccessDate <p>分账完成时间</p>
     *
     * @return $this
     */
    public function setDivideBackSuccessDate($divideBackSuccessDate)
    {
        $this->container['divideBackSuccessDate'] = $divideBackSuccessDate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


