<?php
/**
 * YopYeeDivideRuleRespDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 分账
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Divide\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * YopYeeDivideRuleRespDTO Class Doc Comment
 *
 * @category Class
 * @description 规则明细返参
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class YopYeeDivideRuleRespDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'YopYeeDivideRuleRespDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'merchantNo' => 'string',
        'ruleName' => 'string',
        'ruleNo' => 'string',
        'executeCycleType' => 'string',
        'executeDate' => 'float',
        'amountLimitRuleType' => 'string',
        'withinCycleStartDate' => 'float',
        'fundType' => 'string',
        'executeTime' => 'string',
        'effectiveDate' => 'string',
        'status' => 'string',
        'lastModifyDate' => 'string',
        'batchNotifyUrl' => 'string',
        'divideDetail' => '\Yeepay\Yop\Sdk\Service\Divide\Model\YopYeeDivideRuleDetailRespDTO[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'merchantNo' => null,
        'ruleName' => null,
        'ruleNo' => null,
        'executeCycleType' => null,
        'executeDate' => null,
        'amountLimitRuleType' => null,
        'withinCycleStartDate' => null,
        'fundType' => null,
        'executeTime' => null,
        'effectiveDate' => null,
        'status' => null,
        'lastModifyDate' => null,
        'batchNotifyUrl' => 'notify-url',
        'divideDetail' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'merchantNo' => 'merchantNo',
        'ruleName' => 'ruleName',
        'ruleNo' => 'ruleNo',
        'executeCycleType' => 'executeCycleType',
        'executeDate' => 'executeDate',
        'amountLimitRuleType' => 'amountLimitRuleType',
        'withinCycleStartDate' => 'withinCycleStartDate',
        'fundType' => 'fundType',
        'executeTime' => 'executeTime',
        'effectiveDate' => 'effectiveDate',
        'status' => 'status',
        'lastModifyDate' => 'lastModifyDate',
        'batchNotifyUrl' => 'batchNotifyUrl',
        'divideDetail' => 'divideDetail'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'merchantNo' => 'setMerchantNo',
        'ruleName' => 'setRuleName',
        'ruleNo' => 'setRuleNo',
        'executeCycleType' => 'setExecuteCycleType',
        'executeDate' => 'setExecuteDate',
        'amountLimitRuleType' => 'setAmountLimitRuleType',
        'withinCycleStartDate' => 'setWithinCycleStartDate',
        'fundType' => 'setFundType',
        'executeTime' => 'setExecuteTime',
        'effectiveDate' => 'setEffectiveDate',
        'status' => 'setStatus',
        'lastModifyDate' => 'setLastModifyDate',
        'batchNotifyUrl' => 'setBatchNotifyUrl',
        'divideDetail' => 'setDivideDetail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'merchantNo' => 'getMerchantNo',
        'ruleName' => 'getRuleName',
        'ruleNo' => 'getRuleNo',
        'executeCycleType' => 'getExecuteCycleType',
        'executeDate' => 'getExecuteDate',
        'amountLimitRuleType' => 'getAmountLimitRuleType',
        'withinCycleStartDate' => 'getWithinCycleStartDate',
        'fundType' => 'getFundType',
        'executeTime' => 'getExecuteTime',
        'effectiveDate' => 'getEffectiveDate',
        'status' => 'getStatus',
        'lastModifyDate' => 'getLastModifyDate',
        'batchNotifyUrl' => 'getBatchNotifyUrl',
        'divideDetail' => 'getDivideDetail'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
        $this->container['ruleName'] = isset($data['ruleName']) ? $data['ruleName'] : null;
        $this->container['ruleNo'] = isset($data['ruleNo']) ? $data['ruleNo'] : null;
        $this->container['executeCycleType'] = isset($data['executeCycleType']) ? $data['executeCycleType'] : null;
        $this->container['executeDate'] = isset($data['executeDate']) ? $data['executeDate'] : null;
        $this->container['amountLimitRuleType'] = isset($data['amountLimitRuleType']) ? $data['amountLimitRuleType'] : null;
        $this->container['withinCycleStartDate'] = isset($data['withinCycleStartDate']) ? $data['withinCycleStartDate'] : null;
        $this->container['fundType'] = isset($data['fundType']) ? $data['fundType'] : null;
        $this->container['executeTime'] = isset($data['executeTime']) ? $data['executeTime'] : null;
        $this->container['effectiveDate'] = isset($data['effectiveDate']) ? $data['effectiveDate'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['lastModifyDate'] = isset($data['lastModifyDate']) ? $data['lastModifyDate'] : null;
        $this->container['batchNotifyUrl'] = isset($data['batchNotifyUrl']) ? $data['batchNotifyUrl'] : null;
        $this->container['divideDetail'] = isset($data['divideDetail']) ? $data['divideDetail'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo <p>同添加规则入参：</p> <div> <pre>merchantNo</pre> </div>
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }

    /**
     * Gets ruleName
     *
     * @return string
     */
    public function getRuleName()
    {
        return $this->container['ruleName'];
    }

    /**
     * Sets ruleName
     *
     * @param string $ruleName <p>同添加规则入参：</p> <div> <pre>merchantNo</pre> </div>
     *
     * @return $this
     */
    public function setRuleName($ruleName)
    {
        $this->container['ruleName'] = $ruleName;

        return $this;
    }

    /**
     * Gets ruleNo
     *
     * @return string
     */
    public function getRuleNo()
    {
        return $this->container['ruleNo'];
    }

    /**
     * Sets ruleNo
     *
     * @param string $ruleNo ruleNo
     *
     * @return $this
     */
    public function setRuleNo($ruleNo)
    {
        $this->container['ruleNo'] = $ruleNo;

        return $this;
    }

    /**
     * Gets executeCycleType
     *
     * @return string
     */
    public function getExecuteCycleType()
    {
        return $this->container['executeCycleType'];
    }

    /**
     * Sets executeCycleType
     *
     * @param string $executeCycleType executeCycleType
     *
     * @return $this
     */
    public function setExecuteCycleType($executeCycleType)
    {
        $this->container['executeCycleType'] = $executeCycleType;

        return $this;
    }

    /**
     * Gets executeDate
     *
     * @return float
     */
    public function getExecuteDate()
    {
        return $this->container['executeDate'];
    }

    /**
     * Sets executeDate
     *
     * @param float $executeDate executeDate
     *
     * @return $this
     */
    public function setExecuteDate($executeDate)
    {
        $this->container['executeDate'] = $executeDate;

        return $this;
    }

    /**
     * Gets amountLimitRuleType
     *
     * @return string
     */
    public function getAmountLimitRuleType()
    {
        return $this->container['amountLimitRuleType'];
    }

    /**
     * Sets amountLimitRuleType
     *
     * @param string $amountLimitRuleType amountLimitRuleType
     *
     * @return $this
     */
    public function setAmountLimitRuleType($amountLimitRuleType)
    {
        $this->container['amountLimitRuleType'] = $amountLimitRuleType;

        return $this;
    }

    /**
     * Gets withinCycleStartDate
     *
     * @return float
     */
    public function getWithinCycleStartDate()
    {
        return $this->container['withinCycleStartDate'];
    }

    /**
     * Sets withinCycleStartDate
     *
     * @param float $withinCycleStartDate withinCycleStartDate
     *
     * @return $this
     */
    public function setWithinCycleStartDate($withinCycleStartDate)
    {
        $this->container['withinCycleStartDate'] = $withinCycleStartDate;

        return $this;
    }

    /**
     * Gets fundType
     *
     * @return string
     */
    public function getFundType()
    {
        return $this->container['fundType'];
    }

    /**
     * Sets fundType
     *
     * @param string $fundType fundType
     *
     * @return $this
     */
    public function setFundType($fundType)
    {
        $this->container['fundType'] = $fundType;

        return $this;
    }

    /**
     * Gets executeTime
     *
     * @return string
     */
    public function getExecuteTime()
    {
        return $this->container['executeTime'];
    }

    /**
     * Sets executeTime
     *
     * @param string $executeTime executeTime
     *
     * @return $this
     */
    public function setExecuteTime($executeTime)
    {
        $this->container['executeTime'] = $executeTime;

        return $this;
    }

    /**
     * Gets effectiveDate
     *
     * @return string
     */
    public function getEffectiveDate()
    {
        return $this->container['effectiveDate'];
    }

    /**
     * Sets effectiveDate
     *
     * @param string $effectiveDate effectiveDate
     *
     * @return $this
     */
    public function setEffectiveDate($effectiveDate)
    {
        $this->container['effectiveDate'] = $effectiveDate;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status <div data-page-id=\"JlnbduLJso7HCAxb0hLc9ZZWnbh\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-Krk0duVE0oiH5jxo6jfcfJU6nXe\"><em>VALID(\"生效中\")，</em></div> <div class=\"ace-line ace-line old-record-id-NzlFdiZomojHaixhIKNchqahndh\">WAIT_<em>VALID(\"待生效\"),</em></div> <div class=\"ace-line ace-line old-record-id-P8DCdtEWkoGFwcx9JMJcnhhJnnh\">UN_VALID(\"已失效\")</div> <div class=\"ace-line ace-line old-record-id-QTpedDLDDon5DNxLmJNciNyin8f\">待生效 ：状态=生效，但是未到生效时间</div> <div class=\"ace-line ace-line old-record-id-EfYod09r9oGqndxYVpgctHoXnvg\">生效中 ：状态=生效且已到生效时间</div> <div class=\"ace-line ace-line old-record-id-GzfUd2VInom4J9xl41BcJu9anPb\">已失效 ：状态=已生效，不需要关注生效时间</div> </div>
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets lastModifyDate
     *
     * @return string
     */
    public function getLastModifyDate()
    {
        return $this->container['lastModifyDate'];
    }

    /**
     * Sets lastModifyDate
     *
     * @param string $lastModifyDate <div> <pre>格式：yyyy-MM-dd HH:mm:ss</pre> </div>
     *
     * @return $this
     */
    public function setLastModifyDate($lastModifyDate)
    {
        $this->container['lastModifyDate'] = $lastModifyDate;

        return $this;
    }

    /**
     * Gets batchNotifyUrl
     *
     * @return string
     */
    public function getBatchNotifyUrl()
    {
        return $this->container['batchNotifyUrl'];
    }

    /**
     * Sets batchNotifyUrl
     *
     * @param string $batchNotifyUrl batchNotifyUrl
     *
     * @return $this
     */
    public function setBatchNotifyUrl($batchNotifyUrl)
    {
        $this->container['batchNotifyUrl'] = $batchNotifyUrl;

        return $this;
    }

    /**
     * Gets divideDetail
     *
     * @return \Yeepay\Yop\Sdk\Service\Divide\Model\YopYeeDivideRuleDetailRespDTO[]
     */
    public function getDivideDetail()
    {
        return $this->container['divideDetail'];
    }

    /**
     * Sets divideDetail
     *
     * @param \Yeepay\Yop\Sdk\Service\Divide\Model\YopYeeDivideRuleDetailRespDTO[] $divideDetail divideDetail
     *
     * @return $this
     */
    public function setDivideDetail($divideDetail)
    {
        $this->container['divideDetail'] = $divideDetail;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


