<?php
/**
 * AccountInfoQueryResponseDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 聚合支付
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Aggpay\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * AccountInfoQueryResponseDTO Class Doc Comment
 *
 * @category Class
 * @description 请修改我
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountInfoQueryResponseDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AccountInfoQueryResponseDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'code' => 'string',
        'message' => 'string',
        'status' => 'string',
        'failReason' => 'string',
        'accountNo' => 'string',
        'accountName' => 'string',
        'accountBank' => 'string',
        'accountBankNo' => 'string',
        'accountBankName' => 'string',
        'accountBankDistinctCode' => 'string',
        'accountBankType' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'code' => null,
        'message' => null,
        'status' => null,
        'failReason' => null,
        'accountNo' => null,
        'accountName' => null,
        'accountBank' => null,
        'accountBankNo' => null,
        'accountBankName' => null,
        'accountBankDistinctCode' => null,
        'accountBankType' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'message' => 'message',
        'status' => 'status',
        'failReason' => 'failReason',
        'accountNo' => 'accountNo',
        'accountName' => 'accountName',
        'accountBank' => 'accountBank',
        'accountBankNo' => 'accountBankNo',
        'accountBankName' => 'accountBankName',
        'accountBankDistinctCode' => 'accountBankDistinctCode',
        'accountBankType' => 'accountBankType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'message' => 'setMessage',
        'status' => 'setStatus',
        'failReason' => 'setFailReason',
        'accountNo' => 'setAccountNo',
        'accountName' => 'setAccountName',
        'accountBank' => 'setAccountBank',
        'accountBankNo' => 'setAccountBankNo',
        'accountBankName' => 'setAccountBankName',
        'accountBankDistinctCode' => 'setAccountBankDistinctCode',
        'accountBankType' => 'setAccountBankType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'message' => 'getMessage',
        'status' => 'getStatus',
        'failReason' => 'getFailReason',
        'accountNo' => 'getAccountNo',
        'accountName' => 'getAccountName',
        'accountBank' => 'getAccountBank',
        'accountBankNo' => 'getAccountBankNo',
        'accountBankName' => 'getAccountBankName',
        'accountBankDistinctCode' => 'getAccountBankDistinctCode',
        'accountBankType' => 'getAccountBankType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['code'] = isset($data['code']) ? $data['code'] : null;
        $this->container['message'] = isset($data['message']) ? $data['message'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['failReason'] = isset($data['failReason']) ? $data['failReason'] : null;
        $this->container['accountNo'] = isset($data['accountNo']) ? $data['accountNo'] : null;
        $this->container['accountName'] = isset($data['accountName']) ? $data['accountName'] : null;
        $this->container['accountBank'] = isset($data['accountBank']) ? $data['accountBank'] : null;
        $this->container['accountBankNo'] = isset($data['accountBankNo']) ? $data['accountBankNo'] : null;
        $this->container['accountBankName'] = isset($data['accountBankName']) ? $data['accountBankName'] : null;
        $this->container['accountBankDistinctCode'] = isset($data['accountBankDistinctCode']) ? $data['accountBankDistinctCode'] : null;
        $this->container['accountBankType'] = isset($data['accountBankType']) ? $data['accountBankType'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        if ($this->container['message'] === null) {
            $invalidProperties[] = "'message' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code <p>00000:成功，表示查询成功</p>
     *
     * @return $this
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string $message <p>返回信息</p>
     *
     * @return $this
     */
    public function setMessage($message)
    {
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status <div data-page-id=\"EQSud2ampom8wyxRtG1cWO7onkc\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-Qi27dnopYotXtcxxaVbccbqun6g\">验证状态</div> <div class=\"ace-line ace-line old-record-id-Qi27dnopYotXtcxxaVbccbqun6g\"> <div data-page-id=\"EQSud2ampom8wyxRtG1cWO7onkc\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-DM3fdLhufoYV4XxLpxzcNYVtn7e\">VERIFY_SUCCESS: 验证成功，该账户可正常发起提现。</div> <div class=\"ace-line ace-line old-record-id-DM3fdLhufoYV4XxLpxzcNYVtn7e\">VERIFY_FAIL: 验证失败，该账户无法发起提现，请检查修改。</div> <div class=\"ace-line ace-line old-record-id-DM3fdLhufoYV4XxLpxzcNYVtn7e\">VERIFYING: 验证中，商户可发起提现尝试。</div> </div> </div> </div>
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets failReason
     *
     * @return string
     */
    public function getFailReason()
    {
        return $this->container['failReason'];
    }

    /**
     * Sets failReason
     *
     * @param string $failReason <div data-page-id=\"EQSud2ampom8wyxRtG1cWO7onkc\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-RBPkdGlq7orUzHx4ZANcU9UHnTd\">验证失败原因</div> </div>
     *
     * @return $this
     */
    public function setFailReason($failReason)
    {
        $this->container['failReason'] = $failReason;

        return $this;
    }

    /**
     * Gets accountNo
     *
     * @return string
     */
    public function getAccountNo()
    {
        return $this->container['accountNo'];
    }

    /**
     * Sets accountNo
     *
     * @param string $accountNo <div data-page-id=\"EQSud2ampom8wyxRtG1cWO7onkc\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-XFDbd0Zdvoz7GEx2ycjcSioZnsh\">结算卡号</div> </div>
     *
     * @return $this
     */
    public function setAccountNo($accountNo)
    {
        $this->container['accountNo'] = $accountNo;

        return $this;
    }

    /**
     * Gets accountName
     *
     * @return string
     */
    public function getAccountName()
    {
        return $this->container['accountName'];
    }

    /**
     * Sets accountName
     *
     * @param string $accountName <div data-page-id=\"EQSud2ampom8wyxRtG1cWO7onkc\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-AEjCd3uxsoxrCXxgc7XcOxE2nhe\">结算卡户名</div> </div>
     *
     * @return $this
     */
    public function setAccountName($accountName)
    {
        $this->container['accountName'] = $accountName;

        return $this;
    }

    /**
     * Gets accountBank
     *
     * @return string
     */
    public function getAccountBank()
    {
        return $this->container['accountBank'];
    }

    /**
     * Sets accountBank
     *
     * @param string $accountBank <div data-page-id=\"EQSud2ampom8wyxRtG1cWO7onkc\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-DM9rdc7VwopvtKxA347cgtZ0nGf\">结算卡开户行名称</div> <div class=\"ace-line ace-line old-record-id-DM9rdc7VwopvtKxA347cgtZ0nGf\">枚举详见<a href=\"https://yeepay.feishu.cn/sheets/O9sjs9Qiqho8Hst7F2HcZ3Qbnfg?sheet=BR2vLC\">查询&amp;修改渠道结算信息相关字段</a>枚举中【支持个人银行业务的银行列表】和【支持对公银行业务的银行列表】表单</div> </div>
     *
     * @return $this
     */
    public function setAccountBank($accountBank)
    {
        $this->container['accountBank'] = $accountBank;

        return $this;
    }

    /**
     * Gets accountBankNo
     *
     * @return string
     */
    public function getAccountBankNo()
    {
        return $this->container['accountBankNo'];
    }

    /**
     * Sets accountBankNo
     *
     * @param string $accountBankNo <div data-page-id=\"EQSud2ampom8wyxRtG1cWO7onkc\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-VCuBddxBRo6VS3xzahRcGOeZn63\">结算卡开户行联行号</div> <div class=\"ace-line ace-line old-record-id-VCuBddxBRo6VS3xzahRcGOeZn63\">枚举详见<a href=\"https://yeepay.feishu.cn/sheets/MmMfsrTbnhn744tjYdEcvoNmn83?sheet=0Smsnm\">易宝支付总行编码</a></div> <div class=\"ace-line ace-line old-record-id-VCuBddxBRo6VS3xzahRcGOeZn63\"> <div data-page-id=\"C57DdJHaloryX1xssrjcswA7nDg\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-NxzEdH96co0qX3xCA1gcITvqnnb\">&nbsp;</div> </div> </div> </div>
     *
     * @return $this
     */
    public function setAccountBankNo($accountBankNo)
    {
        $this->container['accountBankNo'] = $accountBankNo;

        return $this;
    }

    /**
     * Gets accountBankName
     *
     * @return string
     */
    public function getAccountBankName()
    {
        return $this->container['accountBankName'];
    }

    /**
     * Sets accountBankName
     *
     * @param string $accountBankName <div data-page-id=\"EQSud2ampom8wyxRtG1cWO7onkc\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-Xi6od4LkWoh4hZxOxMdcLtsWnkh\">结算卡开户行名称</div> <div class=\"ace-line ace-line old-record-id-Xi6od4LkWoh4hZxOxMdcLtsWnkh\">枚举详见<a href=\"https://yeepay.feishu.cn/sheets/KHE9sYFfchk4PXtwNtccsNvmnOb\">开户银行全称（含支行）对照表</a></div> </div>
     *
     * @return $this
     */
    public function setAccountBankName($accountBankName)
    {
        $this->container['accountBankName'] = $accountBankName;

        return $this;
    }

    /**
     * Gets accountBankDistinctCode
     *
     * @return string
     */
    public function getAccountBankDistinctCode()
    {
        return $this->container['accountBankDistinctCode'];
    }

    /**
     * Sets accountBankDistinctCode
     *
     * @param string $accountBankDistinctCode <div data-page-id=\"EQSud2ampom8wyxRtG1cWO7onkc\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-PO87dkUGOoGbUFx2DPAcgXnjnEd\">结算卡开户行区级地区码</div> <div class=\"ace-line ace-line old-record-id-PO87dkUGOoGbUFx2DPAcgXnjnEd\">枚举详见<a href=\"https://yeepay.feishu.cn/sheets/O9sjs9Qiqho8Hst7F2HcZ3Qbnfg?sheet=5e713e\">查询&amp;修改渠道结算信息相关字段</a>枚举中【省市区编码对照表】表单</div> </div>
     *
     * @return $this
     */
    public function setAccountBankDistinctCode($accountBankDistinctCode)
    {
        $this->container['accountBankDistinctCode'] = $accountBankDistinctCode;

        return $this;
    }

    /**
     * Gets accountBankType
     *
     * @return string
     */
    public function getAccountBankType()
    {
        return $this->container['accountBankType'];
    }

    /**
     * Sets accountBankType
     *
     * @param string $accountBankType <div data-page-id=\"EQSud2ampom8wyxRtG1cWO7onkc\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-FLuod8oZHoL8vJxmPszcCNTMn0X\"> <p>结算卡账户类型</p> <div data-page-id=\"C57DdJHaloryX1xssrjcswA7nDg\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-AdXJd44Azo4viUxuqcdcUFoKnwf\">BANK_ACCOUNT_TYPE_CORPORATE：对公银行账户</div> <div class=\"ace-line ace-line old-record-id-AdXJd44Azo4viUxuqcdcUFoKnwf\">BANK_ACCOUNT_TYPE_PERSONAL：经营者个人银行卡</div> </div> </div> </div>
     *
     * @return $this
     */
    public function setAccountBankType($accountBankType)
    {
        $this->container['accountBankType'] = $accountBankType;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


