<?php
/**
 * CreditScoreAuthorizationRequestDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 聚合支付
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Aggpay\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * CreditScoreAuthorizationRequestDTO Class Doc Comment
 *
 * @category Class
 * @description 请修改我
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CreditScoreAuthorizationRequestDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreditScoreAuthorizationRequestDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'parentMerchantNo' => 'string',
        'merchantNo' => 'string',
        'authorizationId' => 'string',
        'channel' => 'string',
        'payWay' => 'string',
        'scene' => 'string',
        'invokeScene' => 'string',
        'appId' => 'string',
        'serviceId' => 'string',
        'notifyUrl' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'parentMerchantNo' => null,
        'merchantNo' => null,
        'authorizationId' => null,
        'channel' => 'enum',
        'payWay' => 'enum',
        'scene' => 'enum',
        'invokeScene' => 'enum',
        'appId' => null,
        'serviceId' => null,
        'notifyUrl' => 'notify-url'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'parentMerchantNo' => 'parentMerchantNo',
        'merchantNo' => 'merchantNo',
        'authorizationId' => 'authorizationId',
        'channel' => 'channel',
        'payWay' => 'payWay',
        'scene' => 'scene',
        'invokeScene' => 'invokeScene',
        'appId' => 'appId',
        'serviceId' => 'serviceId',
        'notifyUrl' => 'notifyUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'parentMerchantNo' => 'setParentMerchantNo',
        'merchantNo' => 'setMerchantNo',
        'authorizationId' => 'setAuthorizationId',
        'channel' => 'setChannel',
        'payWay' => 'setPayWay',
        'scene' => 'setScene',
        'invokeScene' => 'setInvokeScene',
        'appId' => 'setAppId',
        'serviceId' => 'setServiceId',
        'notifyUrl' => 'setNotifyUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'parentMerchantNo' => 'getParentMerchantNo',
        'merchantNo' => 'getMerchantNo',
        'authorizationId' => 'getAuthorizationId',
        'channel' => 'getChannel',
        'payWay' => 'getPayWay',
        'scene' => 'getScene',
        'invokeScene' => 'getInvokeScene',
        'appId' => 'getAppId',
        'serviceId' => 'getServiceId',
        'notifyUrl' => 'getNotifyUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const CHANNEL_WECHAT = 'WECHAT';
    const PAY_WAY_PAY = 'CREDIT_PAY';
    const SCENE_ONLINE = 'ONLINE';
    const INVOKE_SCENE_WECHAT_OFFIACCOUNT = 'WECHAT_OFFIACCOUNT';
    const INVOKE_SCENE_WECHAT_MINI_PROGRAM = 'WECHAT_MINI_PROGRAM';
    const INVOKE_SCENE_SDK = 'SDK';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChannelAllowableValues()
    {
        return [
            self::CHANNEL_WECHAT,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPayWayAllowableValues()
    {
        return [
            self::PAY_WAY_PAY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSceneAllowableValues()
    {
        return [
            self::SCENE_ONLINE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getInvokeSceneAllowableValues()
    {
        return [
            self::INVOKE_SCENE_WECHAT_OFFIACCOUNT,
            self::INVOKE_SCENE_WECHAT_MINI_PROGRAM,
            self::INVOKE_SCENE_SDK,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['parentMerchantNo'] = isset($data['parentMerchantNo']) ? $data['parentMerchantNo'] : null;
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
        $this->container['authorizationId'] = isset($data['authorizationId']) ? $data['authorizationId'] : null;
        $this->container['channel'] = isset($data['channel']) ? $data['channel'] : null;
        $this->container['payWay'] = isset($data['payWay']) ? $data['payWay'] : null;
        $this->container['scene'] = isset($data['scene']) ? $data['scene'] : null;
        $this->container['invokeScene'] = isset($data['invokeScene']) ? $data['invokeScene'] : null;
        $this->container['appId'] = isset($data['appId']) ? $data['appId'] : null;
        $this->container['serviceId'] = isset($data['serviceId']) ? $data['serviceId'] : null;
        $this->container['notifyUrl'] = isset($data['notifyUrl']) ? $data['notifyUrl'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['parentMerchantNo'] === null) {
            $invalidProperties[] = "'parentMerchantNo' can't be null";
        }
        if ($this->container['merchantNo'] === null) {
            $invalidProperties[] = "'merchantNo' can't be null";
        }
        if ($this->container['authorizationId'] === null) {
            $invalidProperties[] = "'authorizationId' can't be null";
        }
        if ($this->container['channel'] === null) {
            $invalidProperties[] = "'channel' can't be null";
        }
        $allowedValues = $this->getChannelAllowableValues();
        if (!is_null($this->container['channel']) && !in_array($this->container['channel'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'channel', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['payWay'] === null) {
            $invalidProperties[] = "'payWay' can't be null";
        }
        $allowedValues = $this->getPayWayAllowableValues();
        if (!is_null($this->container['payWay']) && !in_array($this->container['payWay'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'payWay', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['scene'] === null) {
            $invalidProperties[] = "'scene' can't be null";
        }
        $allowedValues = $this->getSceneAllowableValues();
        if (!is_null($this->container['scene']) && !in_array($this->container['scene'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'scene', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['invokeScene'] === null) {
            $invalidProperties[] = "'invokeScene' can't be null";
        }
        $allowedValues = $this->getInvokeSceneAllowableValues();
        if (!is_null($this->container['invokeScene']) && !in_array($this->container['invokeScene'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'invokeScene', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['appId'] === null) {
            $invalidProperties[] = "'appId' can't be null";
        }
        if ($this->container['serviceId'] === null) {
            $invalidProperties[] = "'serviceId' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets parentMerchantNo
     *
     * @return string
     */
    public function getParentMerchantNo()
    {
        return $this->container['parentMerchantNo'];
    }

    /**
     * Sets parentMerchantNo
     *
     * @param string $parentMerchantNo <p>*标准商户收付款方案中此参数与收款商户编号一致；<br />*平台商户收付款方案中此参数为平台商商户编号；<br />*服务商解决方案中，①标准商户收款时，该参数为标准商户商编 ②平台商收款或平台商入驻商户收款时，该参数为平台商商编。<br />如果商户使用先下单再支付模式，已传入token，则本字段可以不传值，否则必须传值</p>
     *
     * @return $this
     */
    public function setParentMerchantNo($parentMerchantNo)
    {
        $this->container['parentMerchantNo'] = $parentMerchantNo;

        return $this;
    }

    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo merchantNo
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }

    /**
     * Gets authorizationId
     *
     * @return string
     */
    public function getAuthorizationId()
    {
        return $this->container['authorizationId'];
    }

    /**
     * Sets authorizationId
     *
     * @param string $authorizationId authorizationId
     *
     * @return $this
     */
    public function setAuthorizationId($authorizationId)
    {
        $this->container['authorizationId'] = $authorizationId;

        return $this;
    }

    /**
     * Gets channel
     *
     * @return string
     */
    public function getChannel()
    {
        return $this->container['channel'];
    }

    /**
     * Sets channel
     *
     * @param string $channel 可选项如下: WECHAT:微信
     *
     * @return $this
     */
    public function setChannel($channel)
    {
        $allowedValues = $this->getChannelAllowableValues();
        if (!in_array($channel, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'channel', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['channel'] = $channel;

        return $this;
    }

    /**
     * Gets payWay
     *
     * @return string
     */
    public function getPayWay()
    {
        return $this->container['payWay'];
    }

    /**
     * Sets payWay
     *
     * @param string $payWay 可选项如下: CREDIT_PAY:信用分
     *
     * @return $this
     */
    public function setPayWay($payWay)
    {
        $allowedValues = $this->getPayWayAllowableValues();
        if (!in_array($payWay, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'payWay', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['payWay'] = $payWay;

        return $this;
    }

    /**
     * Gets scene
     *
     * @return string
     */
    public function getScene()
    {
        return $this->container['scene'];
    }

    /**
     * Sets scene
     *
     * @param string $scene 可选项如下: ONLINE:线上
     *
     * @return $this
     */
    public function setScene($scene)
    {
        $allowedValues = $this->getSceneAllowableValues();
        if (!in_array($scene, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'scene', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['scene'] = $scene;

        return $this;
    }

    /**
     * Gets invokeScene
     *
     * @return string
     */
    public function getInvokeScene()
    {
        return $this->container['invokeScene'];
    }

    /**
     * Sets invokeScene
     *
     * @param string $invokeScene 可选项如下: WECHAT_OFFIACCOUNT:微信公众号 WECHAT_MINI_PROGRAM:微信小程序 SDK:SDK
     *
     * @return $this
     */
    public function setInvokeScene($invokeScene)
    {
        $allowedValues = $this->getInvokeSceneAllowableValues();
        if (!in_array($invokeScene, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'invokeScene', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['invokeScene'] = $invokeScene;

        return $this;
    }

    /**
     * Gets appId
     *
     * @return string
     */
    public function getAppId()
    {
        return $this->container['appId'];
    }

    /**
     * Sets appId
     *
     * @param string $appId appId
     *
     * @return $this
     */
    public function setAppId($appId)
    {
        $this->container['appId'] = $appId;

        return $this;
    }

    /**
     * Gets serviceId
     *
     * @return string
     */
    public function getServiceId()
    {
        return $this->container['serviceId'];
    }

    /**
     * Sets serviceId
     *
     * @param string $serviceId serviceId
     *
     * @return $this
     */
    public function setServiceId($serviceId)
    {
        $this->container['serviceId'] = $serviceId;

        return $this;
    }

    /**
     * Gets notifyUrl
     *
     * @return string
     */
    public function getNotifyUrl()
    {
        return $this->container['notifyUrl'];
    }

    /**
     * Sets notifyUrl
     *
     * @param string $notifyUrl <p>接收授权结果通知</p>
     *
     * @return $this
     */
    public function setNotifyUrl($notifyUrl)
    {
        $this->container['notifyUrl'] = $notifyUrl;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


