<?php
/**
 * QueryRetailResultInfoDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 聚合支付
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Aggpay\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * QueryRetailResultInfoDTO Class Doc Comment
 *
 * @category Class
 * @description 门店信息
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QueryRetailResultInfoDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'QueryRetailResultInfoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'mobilePhone' => 'string',
        'openId' => 'string',
        'retailName' => 'string',
        'retailType' => 'string',
        'subRetailType' => 'string',
        'legalPersonName' => 'string',
        'enterpriseName' => 'string',
        'registrationNumber' => 'string',
        'retailAddress' => 'string',
        'status' => 'string',
        'grantTime' => 'string',
        'authTime' => 'string',
        'longitude' => 'string',
        'latitude' => 'string',
        'businessTypeList' => 'string[]',
        'otherBusinessType' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'mobilePhone' => null,
        'openId' => null,
        'retailName' => null,
        'retailType' => 'enum',
        'subRetailType' => null,
        'legalPersonName' => null,
        'enterpriseName' => null,
        'registrationNumber' => null,
        'retailAddress' => null,
        'status' => 'enum',
        'grantTime' => null,
        'authTime' => null,
        'longitude' => null,
        'latitude' => null,
        'businessTypeList' => 'enum',
        'otherBusinessType' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'mobilePhone' => 'mobilePhone',
        'openId' => 'openId',
        'retailName' => 'retailName',
        'retailType' => 'retailType',
        'subRetailType' => 'subRetailType',
        'legalPersonName' => 'legalPersonName',
        'enterpriseName' => 'enterpriseName',
        'registrationNumber' => 'registrationNumber',
        'retailAddress' => 'retailAddress',
        'status' => 'status',
        'grantTime' => 'grantTime',
        'authTime' => 'authTime',
        'longitude' => 'longitude',
        'latitude' => 'latitude',
        'businessTypeList' => 'businessTypeList',
        'otherBusinessType' => 'otherBusinessType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'mobilePhone' => 'setMobilePhone',
        'openId' => 'setOpenId',
        'retailName' => 'setRetailName',
        'retailType' => 'setRetailType',
        'subRetailType' => 'setSubRetailType',
        'legalPersonName' => 'setLegalPersonName',
        'enterpriseName' => 'setEnterpriseName',
        'registrationNumber' => 'setRegistrationNumber',
        'retailAddress' => 'setRetailAddress',
        'status' => 'setStatus',
        'grantTime' => 'setGrantTime',
        'authTime' => 'setAuthTime',
        'longitude' => 'setLongitude',
        'latitude' => 'setLatitude',
        'businessTypeList' => 'setBusinessTypeList',
        'otherBusinessType' => 'setOtherBusinessType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'mobilePhone' => 'getMobilePhone',
        'openId' => 'getOpenId',
        'retailName' => 'getRetailName',
        'retailType' => 'getRetailType',
        'subRetailType' => 'getSubRetailType',
        'legalPersonName' => 'getLegalPersonName',
        'enterpriseName' => 'getEnterpriseName',
        'registrationNumber' => 'getRegistrationNumber',
        'retailAddress' => 'getRetailAddress',
        'status' => 'getStatus',
        'grantTime' => 'getGrantTime',
        'authTime' => 'getAuthTime',
        'longitude' => 'getLongitude',
        'latitude' => 'getLatitude',
        'businessTypeList' => 'getBusinessTypeList',
        'otherBusinessType' => 'getOtherBusinessType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const RETAIL_TYPE_GROCERY_STORE = 'GROCERY_STORE';
    const RETAIL_TYPE_CONVENIENCE_STORE = 'CONVENIENCE_STORE';
    const RETAIL_TYPE_SUPERMARKET = 'SUPERMARKET';
    const RETAIL_TYPE_RESTAURANT = 'RESTAURANT';
    const RETAIL_TYPE_BABY_STORE = 'BABY_STORE';
    const RETAIL_TYPE_LIQUOR_STORE = 'LIQUOR_STORE';
    const RETAIL_TYPE_OTHER = 'OTHER';
    const STATUS_AUTHED = 'AUTHED';
    const BUSINESS_TYPE_LIST_FOOD_AND_BEVERAGE = 'FOOD_AND_BEVERAGE';
    const BUSINESS_TYPE_LIST_CATERING = 'CATERING';
    const BUSINESS_TYPE_LIST_FRESH_FRUITS_AND_VEGETABLES = 'FRESH_FRUITS_AND_VEGETABLES';
    const BUSINESS_TYPE_LIST_TOBACCO_AND_ALCOHOL = 'TOBACCO_AND_ALCOHOL';
    const BUSINESS_TYPE_LIST_FOOTWEAR_CLOTHING_UNDERWEAR = 'FOOTWEAR_CLOTHING_UNDERWEAR';
    const BUSINESS_TYPE_LIST_PERSONAL_CARE_AND_COSMETICS = 'PERSONAL_CARE_AND_COSMETICS';
    const BUSINESS_TYPE_LIST_ELECTRONICS = 'ELECTRONICS';
    const BUSINESS_TYPE_LIST_HOME_APPLIANCES = 'HOME_APPLIANCES';
    const BUSINESS_TYPE_LIST_AUTOMOTIVE_REPAIR_PARTS = 'AUTOMOTIVE_REPAIR_PARTS';
    const BUSINESS_TYPE_LIST_MEDICAL_EQUIPMENT = 'MEDICAL_EQUIPMENT';
    const BUSINESS_TYPE_LIST_HOME_IMPROVEMENT_HARDWARE_BUILDING_MATERIALS = 'HOME_IMPROVEMENT_HARDWARE_BUILDING_MATERIALS';
    const BUSINESS_TYPE_LIST_HOME_TEXTILES = 'HOME_TEXTILES';
    const BUSINESS_TYPE_LIST_STATIONERY_TOYS = 'STATIONERY_TOYS';
    const BUSINESS_TYPE_LIST_MATERNITY_BABY = 'MATERNITY_BABY';
    const BUSINESS_TYPE_LIST_PET_PRODUCTS = 'PET_PRODUCTS';
    const BUSINESS_TYPE_LIST_OTHER = 'OTHER';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRetailTypeAllowableValues()
    {
        return [
            self::RETAIL_TYPE_GROCERY_STORE,
            self::RETAIL_TYPE_CONVENIENCE_STORE,
            self::RETAIL_TYPE_SUPERMARKET,
            self::RETAIL_TYPE_RESTAURANT,
            self::RETAIL_TYPE_BABY_STORE,
            self::RETAIL_TYPE_LIQUOR_STORE,
            self::RETAIL_TYPE_OTHER,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_AUTHED,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBusinessTypeListAllowableValues()
    {
        return [
            self::BUSINESS_TYPE_LIST_FOOD_AND_BEVERAGE,
            self::BUSINESS_TYPE_LIST_CATERING,
            self::BUSINESS_TYPE_LIST_FRESH_FRUITS_AND_VEGETABLES,
            self::BUSINESS_TYPE_LIST_TOBACCO_AND_ALCOHOL,
            self::BUSINESS_TYPE_LIST_FOOTWEAR_CLOTHING_UNDERWEAR,
            self::BUSINESS_TYPE_LIST_PERSONAL_CARE_AND_COSMETICS,
            self::BUSINESS_TYPE_LIST_ELECTRONICS,
            self::BUSINESS_TYPE_LIST_HOME_APPLIANCES,
            self::BUSINESS_TYPE_LIST_AUTOMOTIVE_REPAIR_PARTS,
            self::BUSINESS_TYPE_LIST_MEDICAL_EQUIPMENT,
            self::BUSINESS_TYPE_LIST_HOME_IMPROVEMENT_HARDWARE_BUILDING_MATERIALS,
            self::BUSINESS_TYPE_LIST_HOME_TEXTILES,
            self::BUSINESS_TYPE_LIST_STATIONERY_TOYS,
            self::BUSINESS_TYPE_LIST_MATERNITY_BABY,
            self::BUSINESS_TYPE_LIST_PET_PRODUCTS,
            self::BUSINESS_TYPE_LIST_OTHER,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['mobilePhone'] = isset($data['mobilePhone']) ? $data['mobilePhone'] : null;
        $this->container['openId'] = isset($data['openId']) ? $data['openId'] : null;
        $this->container['retailName'] = isset($data['retailName']) ? $data['retailName'] : null;
        $this->container['retailType'] = isset($data['retailType']) ? $data['retailType'] : null;
        $this->container['subRetailType'] = isset($data['subRetailType']) ? $data['subRetailType'] : null;
        $this->container['legalPersonName'] = isset($data['legalPersonName']) ? $data['legalPersonName'] : null;
        $this->container['enterpriseName'] = isset($data['enterpriseName']) ? $data['enterpriseName'] : null;
        $this->container['registrationNumber'] = isset($data['registrationNumber']) ? $data['registrationNumber'] : null;
        $this->container['retailAddress'] = isset($data['retailAddress']) ? $data['retailAddress'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['grantTime'] = isset($data['grantTime']) ? $data['grantTime'] : null;
        $this->container['authTime'] = isset($data['authTime']) ? $data['authTime'] : null;
        $this->container['longitude'] = isset($data['longitude']) ? $data['longitude'] : null;
        $this->container['latitude'] = isset($data['latitude']) ? $data['latitude'] : null;
        $this->container['businessTypeList'] = isset($data['businessTypeList']) ? $data['businessTypeList'] : null;
        $this->container['otherBusinessType'] = isset($data['otherBusinessType']) ? $data['otherBusinessType'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getRetailTypeAllowableValues();
        if (!is_null($this->container['retailType']) && !in_array($this->container['retailType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'retailType', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets mobilePhone
     *
     * @return string
     */
    public function getMobilePhone()
    {
        return $this->container['mobilePhone'];
    }

    /**
     * Sets mobilePhone
     *
     * @param string $mobilePhone <p>手机号</p>
     *
     * @return $this
     */
    public function setMobilePhone($mobilePhone)
    {
        $this->container['mobilePhone'] = $mobilePhone;

        return $this;
    }

    /**
     * Gets openId
     *
     * @return string
     */
    public function getOpenId()
    {
        return $this->container['openId'];
    }

    /**
     * Sets openId
     *
     * @param string $openId <p>门店负责人openid</p>
     *
     * @return $this
     */
    public function setOpenId($openId)
    {
        $this->container['openId'] = $openId;

        return $this;
    }

    /**
     * Gets retailName
     *
     * @return string
     */
    public function getRetailName()
    {
        return $this->container['retailName'];
    }

    /**
     * Sets retailName
     *
     * @param string $retailName <p>门店名称</p>
     *
     * @return $this
     */
    public function setRetailName($retailName)
    {
        $this->container['retailName'] = $retailName;

        return $this;
    }

    /**
     * Gets retailType
     *
     * @return string
     */
    public function getRetailType()
    {
        return $this->container['retailType'];
    }

    /**
     * Sets retailType
     *
     * @param string $retailType <p>一级门店类型</p> 可选项如下: GROCERY_STORE:杂货店 CONVENIENCE_STORE:便利店 SUPERMARKET:超市 RESTAURANT:餐饮店 BABY_STORE:母婴店 LIQUOR_STORE:烟酒店 OTHER:其他
     *
     * @return $this
     */
    public function setRetailType($retailType)
    {
        $allowedValues = $this->getRetailTypeAllowableValues();
        if (!is_null($retailType) && !in_array($retailType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'retailType', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['retailType'] = $retailType;

        return $this;
    }

    /**
     * Gets subRetailType
     *
     * @return string
     */
    public function getSubRetailType()
    {
        return $this->container['subRetailType'];
    }

    /**
     * Sets subRetailType
     *
     * @param string $subRetailType <p>二级门店类型</p>
     *
     * @return $this
     */
    public function setSubRetailType($subRetailType)
    {
        $this->container['subRetailType'] = $subRetailType;

        return $this;
    }

    /**
     * Gets legalPersonName
     *
     * @return string
     */
    public function getLegalPersonName()
    {
        return $this->container['legalPersonName'];
    }

    /**
     * Sets legalPersonName
     *
     * @param string $legalPersonName <p>法人姓名</p>
     *
     * @return $this
     */
    public function setLegalPersonName($legalPersonName)
    {
        $this->container['legalPersonName'] = $legalPersonName;

        return $this;
    }

    /**
     * Gets enterpriseName
     *
     * @return string
     */
    public function getEnterpriseName()
    {
        return $this->container['enterpriseName'];
    }

    /**
     * Sets enterpriseName
     *
     * @param string $enterpriseName <p>企业名称</p>
     *
     * @return $this
     */
    public function setEnterpriseName($enterpriseName)
    {
        $this->container['enterpriseName'] = $enterpriseName;

        return $this;
    }

    /**
     * Gets registrationNumber
     *
     * @return string
     */
    public function getRegistrationNumber()
    {
        return $this->container['registrationNumber'];
    }

    /**
     * Sets registrationNumber
     *
     * @param string $registrationNumber <p>营业执照注册号</p>
     *
     * @return $this
     */
    public function setRegistrationNumber($registrationNumber)
    {
        $this->container['registrationNumber'] = $registrationNumber;

        return $this;
    }

    /**
     * Gets retailAddress
     *
     * @return string
     */
    public function getRetailAddress()
    {
        return $this->container['retailAddress'];
    }

    /**
     * Sets retailAddress
     *
     * @param string $retailAddress <p>门店地址</p>
     *
     * @return $this
     */
    public function setRetailAddress($retailAddress)
    {
        $this->container['retailAddress'] = $retailAddress;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status <p>认证状态</p> 可选项如下: AUTHED:已完成认证
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($status) && !in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets grantTime
     *
     * @return string
     */
    public function getGrantTime()
    {
        return $this->container['grantTime'];
    }

    /**
     * Sets grantTime
     *
     * @param string $grantTime <p>授权时间，授权给小程序那一刻的时间戳</p>
     *
     * @return $this
     */
    public function setGrantTime($grantTime)
    {
        $this->container['grantTime'] = $grantTime;

        return $this;
    }

    /**
     * Gets authTime
     *
     * @return string
     */
    public function getAuthTime()
    {
        return $this->container['authTime'];
    }

    /**
     * Sets authTime
     *
     * @param string $authTime <p>认证时间，认证完成那一刻的时间戳</p>
     *
     * @return $this
     */
    public function setAuthTime($authTime)
    {
        $this->container['authTime'] = $authTime;

        return $this;
    }

    /**
     * Gets longitude
     *
     * @return string
     */
    public function getLongitude()
    {
        return $this->container['longitude'];
    }

    /**
     * Sets longitude
     *
     * @param string $longitude <p>经度（门店定位信息。若门店未提交定位信息，则返回值里无该字段）</p>
     *
     * @return $this
     */
    public function setLongitude($longitude)
    {
        $this->container['longitude'] = $longitude;

        return $this;
    }

    /**
     * Gets latitude
     *
     * @return string
     */
    public function getLatitude()
    {
        return $this->container['latitude'];
    }

    /**
     * Sets latitude
     *
     * @param string $latitude <p>纬度（门店定位信息。若门店未提交定位信息，则返回值里无该字段）</p>
     *
     * @return $this
     */
    public function setLatitude($latitude)
    {
        $this->container['latitude'] = $latitude;

        return $this;
    }

    /**
     * Gets businessTypeList
     *
     * @return string[]
     */
    public function getBusinessTypeList()
    {
        return $this->container['businessTypeList'];
    }

    /**
     * Sets businessTypeList
     *
     * @param string[] $businessTypeList <p>可选项如下:</p> <ul> <li>FOOD_AND_BEVERAGE:食品饮料</li> <li>CATERING:餐饮 </li> <li>FRESH_FRUITS_AND_VEGETABLES:生鲜果蔬（含鲜花） </li> <li>TOBACCO_AND_ALCOHOL:烟酒 </li> <li>FOOTWEAR_CLOTHING_UNDERWEAR:鞋服内衣 </li> <li>PERSONAL_CARE_AND_COSMETICS:个护美妆 </li> <li>ELECTRONICS:3C数码</li> <li>HOME_APPLIANCES:家用电器 </li> <li>AUTOMOTIVE_REPAIR_PARTS:汽修/汽配 </li> <li>MEDICAL_EQUIPMENT:医药/医疗器械 </li> <li>HOME_IMPROVEMENT_HARDWARE_B</li> <li>UILDING_MATERIALS:家装/五金/建材 </li> <li>HOME_TEXTILES:家居家纺 </li> <li>STATIONERY_TOYS:文具玩具 </li> <li>MATERNITY_BABY:母婴 </li> <li>PET_PRODUCTS:宠物 </li> <li>OTHER:其他</li> </ul>
     *
     * @return $this
     */
    public function setBusinessTypeList($businessTypeList)
    {
        $allowedValues = $this->getBusinessTypeListAllowableValues();
        if (!is_null($businessTypeList) && array_diff($businessTypeList, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'businessTypeList', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['businessTypeList'] = $businessTypeList;

        return $this;
    }

    /**
     * Gets otherBusinessType
     *
     * @return string
     */
    public function getOtherBusinessType()
    {
        return $this->container['otherBusinessType'];
    }

    /**
     * Sets otherBusinessType
     *
     * @param string $otherBusinessType otherBusinessType
     *
     * @return $this
     */
    public function setOtherBusinessType($otherBusinessType)
    {
        $this->container['otherBusinessType'] = $otherBusinessType;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


