<?php
/**
 * WechatGoodsDetail
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 聚合支付
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Aggpay\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * WechatGoodsDetail Class Doc Comment
 *
 * @category Class
 * @description 【优惠功能】
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WechatGoodsDetail implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WechatGoodsDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'goodsDetails' => '\Yeepay\Yop\Sdk\Service\Aggpay\Model\WechatGoodsDetailGoodsDetail[]',
        'costPrice' => 'string',
        'receiptId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'goodsDetails' => null,
        'costPrice' => null,
        'receiptId' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'goodsDetails' => 'goodsDetails',
        'costPrice' => 'costPrice',
        'receiptId' => 'receiptId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'goodsDetails' => 'setGoodsDetails',
        'costPrice' => 'setCostPrice',
        'receiptId' => 'setReceiptId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'goodsDetails' => 'getGoodsDetails',
        'costPrice' => 'getCostPrice',
        'receiptId' => 'getReceiptId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['goodsDetails'] = isset($data['goodsDetails']) ? $data['goodsDetails'] : null;
        $this->container['costPrice'] = isset($data['costPrice']) ? $data['costPrice'] : null;
        $this->container['receiptId'] = isset($data['receiptId']) ? $data['receiptId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets goodsDetails
     *
     * @return \Yeepay\Yop\Sdk\Service\Aggpay\Model\WechatGoodsDetailGoodsDetail[]
     */
    public function getGoodsDetails()
    {
        return $this->container['goodsDetails'];
    }

    /**
     * Sets goodsDetails
     *
     * @param \Yeepay\Yop\Sdk\Service\Aggpay\Model\WechatGoodsDetailGoodsDetail[] $goodsDetails <p class=\"iwiki-p\">【单品列表】&nbsp;单品列表信息</p> <p class=\"iwiki-p\">&nbsp;</p>
     *
     * @return $this
     */
    public function setGoodsDetails($goodsDetails)
    {
        $this->container['goodsDetails'] = $goodsDetails;

        return $this;
    }

    /**
     * Gets costPrice
     *
     * @return string
     */
    public function getCostPrice()
    {
        return $this->container['costPrice'];
    }

    /**
     * Sets costPrice
     *
     * @param string $costPrice <p class=\"iwiki-p\">【订单原价】</p> <p class=\"iwiki-p\">1、商户侧一张小票订单可能被分多次支付，订单原价用于记录整张小票的交易金额。</p> <p class=\"iwiki-p\">2、当订单原价与支付金额不相等，则不享受优惠。</p> <p class=\"iwiki-p\">3、该字段主要用于防止同一张小票分多次支付，以享受多次优惠的情况，正常支付订单不必上传此参数。</p>
     *
     * @return $this
     */
    public function setCostPrice($costPrice)
    {
        $this->container['costPrice'] = $costPrice;

        return $this;
    }

    /**
     * Gets receiptId
     *
     * @return string
     */
    public function getReceiptId()
    {
        return $this->container['receiptId'];
    }

    /**
     * Sets receiptId
     *
     * @param string $receiptId <p>商家小票 ID</p>
     *
     * @return $this
     */
    public function setReceiptId($receiptId)
    {
        $this->container['receiptId'] = $receiptId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


