<?php
/**
 * OpenAccountRequestDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 金融业务组
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Financial\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * OpenAccountRequestDTO Class Doc Comment
 *
 * @category Class
 * @description 开户申请请求参数
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OpenAccountRequestDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OpenAccountRequestDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'parentMerchantNo' => 'string',
        'merchantNo' => 'string',
        'requestNo' => 'string',
        'topAccountNo' => 'string',
        'bankCode' => 'string',
        'businessCardType' => 'string',
        'socialCreditCode' => 'string',
        'extParam' => '\Yeepay\Yop\Sdk\Service\Financial\Model\FJHTRequestDTO',
        'notifyUrl' => 'string',
        'remark' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'parentMerchantNo' => null,
        'merchantNo' => null,
        'requestNo' => null,
        'topAccountNo' => null,
        'bankCode' => null,
        'businessCardType' => 'enum',
        'socialCreditCode' => null,
        'extParam' => null,
        'notifyUrl' => 'notify-url',
        'remark' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'parentMerchantNo' => 'parentMerchantNo',
        'merchantNo' => 'merchantNo',
        'requestNo' => 'requestNo',
        'topAccountNo' => 'topAccountNo',
        'bankCode' => 'bankCode',
        'businessCardType' => 'businessCardType',
        'socialCreditCode' => 'socialCreditCode',
        'extParam' => 'extParam',
        'notifyUrl' => 'notifyUrl',
        'remark' => 'remark'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'parentMerchantNo' => 'setParentMerchantNo',
        'merchantNo' => 'setMerchantNo',
        'requestNo' => 'setRequestNo',
        'topAccountNo' => 'setTopAccountNo',
        'bankCode' => 'setBankCode',
        'businessCardType' => 'setBusinessCardType',
        'socialCreditCode' => 'setSocialCreditCode',
        'extParam' => 'setExtParam',
        'notifyUrl' => 'setNotifyUrl',
        'remark' => 'setRemark'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'parentMerchantNo' => 'getParentMerchantNo',
        'merchantNo' => 'getMerchantNo',
        'requestNo' => 'getRequestNo',
        'topAccountNo' => 'getTopAccountNo',
        'bankCode' => 'getBankCode',
        'businessCardType' => 'getBusinessCardType',
        'socialCreditCode' => 'getSocialCreditCode',
        'extParam' => 'getExtParam',
        'notifyUrl' => 'getNotifyUrl',
        'remark' => 'getRemark'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const BUSINESS_CARD_TYPE_BUSINESS_LICENSE = 'BUSINESS_LICENSE';
    const BUSINESS_CARD_TYPE_OTHER_LICENSE = 'OTHER_LICENSE';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBusinessCardTypeAllowableValues()
    {
        return [
            self::BUSINESS_CARD_TYPE_BUSINESS_LICENSE,
            self::BUSINESS_CARD_TYPE_OTHER_LICENSE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['parentMerchantNo'] = isset($data['parentMerchantNo']) ? $data['parentMerchantNo'] : null;
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
        $this->container['requestNo'] = isset($data['requestNo']) ? $data['requestNo'] : null;
        $this->container['topAccountNo'] = isset($data['topAccountNo']) ? $data['topAccountNo'] : null;
        $this->container['bankCode'] = isset($data['bankCode']) ? $data['bankCode'] : null;
        $this->container['businessCardType'] = isset($data['businessCardType']) ? $data['businessCardType'] : null;
        $this->container['socialCreditCode'] = isset($data['socialCreditCode']) ? $data['socialCreditCode'] : null;
        $this->container['extParam'] = isset($data['extParam']) ? $data['extParam'] : null;
        $this->container['notifyUrl'] = isset($data['notifyUrl']) ? $data['notifyUrl'] : null;
        $this->container['remark'] = isset($data['remark']) ? $data['remark'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['parentMerchantNo'] === null) {
            $invalidProperties[] = "'parentMerchantNo' can't be null";
        }
        if ($this->container['merchantNo'] === null) {
            $invalidProperties[] = "'merchantNo' can't be null";
        }
        if ($this->container['requestNo'] === null) {
            $invalidProperties[] = "'requestNo' can't be null";
        }
        if ($this->container['topAccountNo'] === null) {
            $invalidProperties[] = "'topAccountNo' can't be null";
        }
        if ($this->container['bankCode'] === null) {
            $invalidProperties[] = "'bankCode' can't be null";
        }
        if ($this->container['businessCardType'] === null) {
            $invalidProperties[] = "'businessCardType' can't be null";
        }
        $allowedValues = $this->getBusinessCardTypeAllowableValues();
        if (!is_null($this->container['businessCardType']) && !in_array($this->container['businessCardType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'businessCardType', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['socialCreditCode'] === null) {
            $invalidProperties[] = "'socialCreditCode' can't be null";
        }
        if ($this->container['extParam'] === null) {
            $invalidProperties[] = "'extParam' can't be null";
        }
        if ($this->container['notifyUrl'] === null) {
            $invalidProperties[] = "'notifyUrl' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets parentMerchantNo
     *
     * @return string
     */
    public function getParentMerchantNo()
    {
        return $this->container['parentMerchantNo'];
    }

    /**
     * Sets parentMerchantNo
     *
     * @param string $parentMerchantNo <p>技术发起方商户编号</p>
     *
     * @return $this
     */
    public function setParentMerchantNo($parentMerchantNo)
    {
        $this->container['parentMerchantNo'] = $parentMerchantNo;

        return $this;
    }

    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo <p>商户编号</p>
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }

    /**
     * Gets requestNo
     *
     * @return string
     */
    public function getRequestNo()
    {
        return $this->container['requestNo'];
    }

    /**
     * Sets requestNo
     *
     * @param string $requestNo <p>商户唯一请求号</p>
     *
     * @return $this
     */
    public function setRequestNo($requestNo)
    {
        $this->container['requestNo'] = $requestNo;

        return $this;
    }

    /**
     * Gets topAccountNo
     *
     * @return string
     */
    public function getTopAccountNo()
    {
        return $this->container['topAccountNo'];
    }

    /**
     * Sets topAccountNo
     *
     * @param string $topAccountNo <p>HT银行顶点账户</p>
     *
     * @return $this
     */
    public function setTopAccountNo($topAccountNo)
    {
        $this->container['topAccountNo'] = $topAccountNo;

        return $this;
    }

    /**
     * Gets bankCode
     *
     * @return string
     */
    public function getBankCode()
    {
        return $this->container['bankCode'];
    }

    /**
     * Sets bankCode
     *
     * @param string $bankCode <p>HT银行：FJHTB</p>
     *
     * @return $this
     */
    public function setBankCode($bankCode)
    {
        $this->container['bankCode'] = $bankCode;

        return $this;
    }

    /**
     * Gets businessCardType
     *
     * @return string
     */
    public function getBusinessCardType()
    {
        return $this->container['businessCardType'];
    }

    /**
     * Sets businessCardType
     *
     * @param string $businessCardType 可选项如下: BUSINESS_LICENSE:营业执照 OTHER_LICENSE:其他
     *
     * @return $this
     */
    public function setBusinessCardType($businessCardType)
    {
        $allowedValues = $this->getBusinessCardTypeAllowableValues();
        if (!in_array($businessCardType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'businessCardType', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['businessCardType'] = $businessCardType;

        return $this;
    }

    /**
     * Gets socialCreditCode
     *
     * @return string
     */
    public function getSocialCreditCode()
    {
        return $this->container['socialCreditCode'];
    }

    /**
     * Sets socialCreditCode
     *
     * @param string $socialCreditCode socialCreditCode
     *
     * @return $this
     */
    public function setSocialCreditCode($socialCreditCode)
    {
        $this->container['socialCreditCode'] = $socialCreditCode;

        return $this;
    }

    /**
     * Gets extParam
     *
     * @return \Yeepay\Yop\Sdk\Service\Financial\Model\FJHTRequestDTO
     */
    public function getExtParam()
    {
        return $this->container['extParam'];
    }

    /**
     * Sets extParam
     *
     * @param \Yeepay\Yop\Sdk\Service\Financial\Model\FJHTRequestDTO $extParam extParam
     *
     * @return $this
     */
    public function setExtParam($extParam)
    {
        $this->container['extParam'] = $extParam;

        return $this;
    }

    /**
     * Gets notifyUrl
     *
     * @return string
     */
    public function getNotifyUrl()
    {
        return $this->container['notifyUrl'];
    }

    /**
     * Sets notifyUrl
     *
     * @param string $notifyUrl notifyUrl
     *
     * @return $this
     */
    public function setNotifyUrl($notifyUrl)
    {
        $this->container['notifyUrl'] = $notifyUrl;

        return $this;
    }

    /**
     * Gets remark
     *
     * @return string
     */
    public function getRemark()
    {
        return $this->container['remark'];
    }

    /**
     * Sets remark
     *
     * @param string $remark remark
     *
     * @return $this
     */
    public function setRemark($remark)
    {
        $this->container['remark'] = $remark;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


