<?php
/**
 * BankAccountOpenWhlhbDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 账户
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Account\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * BankAccountOpenWhlhbDTO Class Doc Comment
 *
 * @category Class
 * @description 蓝海银行拓展参数
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BankAccountOpenWhlhbDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BankAccountOpenWhlhbDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'businessLicenceEffectiveDate' => 'string',
        'businessLicenceExpirationDate' => 'string',
        'taxNo' => 'string',
        'taxPicUrl' => 'string',
        'organizationNo' => 'string',
        'organizationImage' => 'string',
        'legalNation' => 'string',
        'legalGender' => 'string',
        'legalMobile' => 'string',
        'legalContactAddress' => 'string',
        'legalCardCreateUnit' => 'string',
        'legalLicenceEffectiveDate' => 'string',
        'legalLicenceExpirationDate' => 'string',
        'benefitInfoDTOList' => '\Yeepay\Yop\Sdk\Service\Account\Model\WhLhbBenefitDTO[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'businessLicenceEffectiveDate' => null,
        'businessLicenceExpirationDate' => null,
        'taxNo' => null,
        'taxPicUrl' => null,
        'organizationNo' => null,
        'organizationImage' => null,
        'legalNation' => null,
        'legalGender' => 'enum',
        'legalMobile' => null,
        'legalContactAddress' => null,
        'legalCardCreateUnit' => null,
        'legalLicenceEffectiveDate' => null,
        'legalLicenceExpirationDate' => null,
        'benefitInfoDTOList' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'businessLicenceEffectiveDate' => 'businessLicenceEffectiveDate',
        'businessLicenceExpirationDate' => 'businessLicenceExpirationDate',
        'taxNo' => 'taxNo',
        'taxPicUrl' => 'taxPicUrl',
        'organizationNo' => 'organizationNo',
        'organizationImage' => 'organizationImage',
        'legalNation' => 'legalNation',
        'legalGender' => 'legalGender',
        'legalMobile' => 'legalMobile',
        'legalContactAddress' => 'legalContactAddress',
        'legalCardCreateUnit' => 'legalCardCreateUnit',
        'legalLicenceEffectiveDate' => 'legalLicenceEffectiveDate',
        'legalLicenceExpirationDate' => 'legalLicenceExpirationDate',
        'benefitInfoDTOList' => 'benefitInfoDTOList'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'businessLicenceEffectiveDate' => 'setBusinessLicenceEffectiveDate',
        'businessLicenceExpirationDate' => 'setBusinessLicenceExpirationDate',
        'taxNo' => 'setTaxNo',
        'taxPicUrl' => 'setTaxPicUrl',
        'organizationNo' => 'setOrganizationNo',
        'organizationImage' => 'setOrganizationImage',
        'legalNation' => 'setLegalNation',
        'legalGender' => 'setLegalGender',
        'legalMobile' => 'setLegalMobile',
        'legalContactAddress' => 'setLegalContactAddress',
        'legalCardCreateUnit' => 'setLegalCardCreateUnit',
        'legalLicenceEffectiveDate' => 'setLegalLicenceEffectiveDate',
        'legalLicenceExpirationDate' => 'setLegalLicenceExpirationDate',
        'benefitInfoDTOList' => 'setBenefitInfoDTOList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'businessLicenceEffectiveDate' => 'getBusinessLicenceEffectiveDate',
        'businessLicenceExpirationDate' => 'getBusinessLicenceExpirationDate',
        'taxNo' => 'getTaxNo',
        'taxPicUrl' => 'getTaxPicUrl',
        'organizationNo' => 'getOrganizationNo',
        'organizationImage' => 'getOrganizationImage',
        'legalNation' => 'getLegalNation',
        'legalGender' => 'getLegalGender',
        'legalMobile' => 'getLegalMobile',
        'legalContactAddress' => 'getLegalContactAddress',
        'legalCardCreateUnit' => 'getLegalCardCreateUnit',
        'legalLicenceEffectiveDate' => 'getLegalLicenceEffectiveDate',
        'legalLicenceExpirationDate' => 'getLegalLicenceExpirationDate',
        'benefitInfoDTOList' => 'getBenefitInfoDTOList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const LEGAL_GENDER_MALE = 'MALE';
    const LEGAL_GENDER_FMALE = 'FMALE';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLegalGenderAllowableValues()
    {
        return [
            self::LEGAL_GENDER_MALE,
            self::LEGAL_GENDER_FMALE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['businessLicenceEffectiveDate'] = isset($data['businessLicenceEffectiveDate']) ? $data['businessLicenceEffectiveDate'] : null;
        $this->container['businessLicenceExpirationDate'] = isset($data['businessLicenceExpirationDate']) ? $data['businessLicenceExpirationDate'] : null;
        $this->container['taxNo'] = isset($data['taxNo']) ? $data['taxNo'] : null;
        $this->container['taxPicUrl'] = isset($data['taxPicUrl']) ? $data['taxPicUrl'] : null;
        $this->container['organizationNo'] = isset($data['organizationNo']) ? $data['organizationNo'] : null;
        $this->container['organizationImage'] = isset($data['organizationImage']) ? $data['organizationImage'] : null;
        $this->container['legalNation'] = isset($data['legalNation']) ? $data['legalNation'] : null;
        $this->container['legalGender'] = isset($data['legalGender']) ? $data['legalGender'] : null;
        $this->container['legalMobile'] = isset($data['legalMobile']) ? $data['legalMobile'] : null;
        $this->container['legalContactAddress'] = isset($data['legalContactAddress']) ? $data['legalContactAddress'] : null;
        $this->container['legalCardCreateUnit'] = isset($data['legalCardCreateUnit']) ? $data['legalCardCreateUnit'] : null;
        $this->container['legalLicenceEffectiveDate'] = isset($data['legalLicenceEffectiveDate']) ? $data['legalLicenceEffectiveDate'] : null;
        $this->container['legalLicenceExpirationDate'] = isset($data['legalLicenceExpirationDate']) ? $data['legalLicenceExpirationDate'] : null;
        $this->container['benefitInfoDTOList'] = isset($data['benefitInfoDTOList']) ? $data['benefitInfoDTOList'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['legalNation'] === null) {
            $invalidProperties[] = "'legalNation' can't be null";
        }
        if ($this->container['legalGender'] === null) {
            $invalidProperties[] = "'legalGender' can't be null";
        }
        $allowedValues = $this->getLegalGenderAllowableValues();
        if (!is_null($this->container['legalGender']) && !in_array($this->container['legalGender'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'legalGender', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['legalMobile'] === null) {
            $invalidProperties[] = "'legalMobile' can't be null";
        }
        if ($this->container['legalContactAddress'] === null) {
            $invalidProperties[] = "'legalContactAddress' can't be null";
        }
        if ($this->container['legalCardCreateUnit'] === null) {
            $invalidProperties[] = "'legalCardCreateUnit' can't be null";
        }
        if ($this->container['benefitInfoDTOList'] === null) {
            $invalidProperties[] = "'benefitInfoDTOList' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets businessLicenceEffectiveDate
     *
     * @return string
     */
    public function getBusinessLicenceEffectiveDate()
    {
        return $this->container['businessLicenceEffectiveDate'];
    }

    /**
     * Sets businessLicenceEffectiveDate
     *
     * @param string $businessLicenceEffectiveDate <p>参数格式为yyyyMMdd</p>
     *
     * @return $this
     */
    public function setBusinessLicenceEffectiveDate($businessLicenceEffectiveDate)
    {
        $this->container['businessLicenceEffectiveDate'] = $businessLicenceEffectiveDate;

        return $this;
    }

    /**
     * Gets businessLicenceExpirationDate
     *
     * @return string
     */
    public function getBusinessLicenceExpirationDate()
    {
        return $this->container['businessLicenceExpirationDate'];
    }

    /**
     * Sets businessLicenceExpirationDate
     *
     * @param string $businessLicenceExpirationDate <p>参数格式为yyyyMMdd或者forever</p>
     *
     * @return $this
     */
    public function setBusinessLicenceExpirationDate($businessLicenceExpirationDate)
    {
        $this->container['businessLicenceExpirationDate'] = $businessLicenceExpirationDate;

        return $this;
    }

    /**
     * Gets taxNo
     *
     * @return string
     */
    public function getTaxNo()
    {
        return $this->container['taxNo'];
    }

    /**
     * Sets taxNo
     *
     * @param string $taxNo <p>税务登记号</p>
     *
     * @return $this
     */
    public function setTaxNo($taxNo)
    {
        $this->container['taxNo'] = $taxNo;

        return $this;
    }

    /**
     * Gets taxPicUrl
     *
     * @return string
     */
    public function getTaxPicUrl()
    {
        return $this->container['taxPicUrl'];
    }

    /**
     * Sets taxPicUrl
     *
     * @param string $taxPicUrl <p>税务登记照片证</p>
     *
     * @return $this
     */
    public function setTaxPicUrl($taxPicUrl)
    {
        $this->container['taxPicUrl'] = $taxPicUrl;

        return $this;
    }

    /**
     * Gets organizationNo
     *
     * @return string
     */
    public function getOrganizationNo()
    {
        return $this->container['organizationNo'];
    }

    /**
     * Sets organizationNo
     *
     * @param string $organizationNo <p>组织机构代码证号</p>
     *
     * @return $this
     */
    public function setOrganizationNo($organizationNo)
    {
        $this->container['organizationNo'] = $organizationNo;

        return $this;
    }

    /**
     * Gets organizationImage
     *
     * @return string
     */
    public function getOrganizationImage()
    {
        return $this->container['organizationImage'];
    }

    /**
     * Sets organizationImage
     *
     * @param string $organizationImage <p>组织机构代码证URL</p>
     *
     * @return $this
     */
    public function setOrganizationImage($organizationImage)
    {
        $this->container['organizationImage'] = $organizationImage;

        return $this;
    }

    /**
     * Gets legalNation
     *
     * @return string
     */
    public function getLegalNation()
    {
        return $this->container['legalNation'];
    }

    /**
     * Sets legalNation
     *
     * @param string $legalNation <p>可选项如下：<br />汉族<br />蒙古族<br />回族<br />藏族<br />维吾尔族<br />苗族<br />彝族<br />壮族<br />布依族<br />朝鲜族<br />满族<br />侗族<br />瑶族<br />白族<br />土家族<br />哈尼族<br />哈萨克族<br />傣族<br />黎族<br />傈僳族<br />佤族<br />畲族<br />高山族<br />拉祜族<br />水族<br />东乡族<br />纳西族<br />景颇族<br />柯尔克孜族<br />土族<br />达斡尔族<br />仫佬族<br />羌族<br />布朗族<br />撒拉族<br />毛南族<br />仡佬族<br />锡伯族<br />阿昌族<br />普米族<br />塔吉克族<br />怒族<br />乌孜别克族<br />俄罗斯族<br />鄂温克族<br />德昂族<br />保安族<br />裕固族<br />京族<br />塔塔尔族<br />独龙族<br />鄂伦春族<br />赫哲族<br />门巴族<br />珞巴族<br />基诺族</p>
     *
     * @return $this
     */
    public function setLegalNation($legalNation)
    {
        $this->container['legalNation'] = $legalNation;

        return $this;
    }

    /**
     * Gets legalGender
     *
     * @return string
     */
    public function getLegalGender()
    {
        return $this->container['legalGender'];
    }

    /**
     * Sets legalGender
     *
     * @param string $legalGender 可选项如下: MALE:男 FMALE:女
     *
     * @return $this
     */
    public function setLegalGender($legalGender)
    {
        $allowedValues = $this->getLegalGenderAllowableValues();
        if (!in_array($legalGender, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'legalGender', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['legalGender'] = $legalGender;

        return $this;
    }

    /**
     * Gets legalMobile
     *
     * @return string
     */
    public function getLegalMobile()
    {
        return $this->container['legalMobile'];
    }

    /**
     * Sets legalMobile
     *
     * @param string $legalMobile <p>法人手机号码</p>
     *
     * @return $this
     */
    public function setLegalMobile($legalMobile)
    {
        $this->container['legalMobile'] = $legalMobile;

        return $this;
    }

    /**
     * Gets legalContactAddress
     *
     * @return string
     */
    public function getLegalContactAddress()
    {
        return $this->container['legalContactAddress'];
    }

    /**
     * Sets legalContactAddress
     *
     * @param string $legalContactAddress <p>法人证件地址</p>
     *
     * @return $this
     */
    public function setLegalContactAddress($legalContactAddress)
    {
        $this->container['legalContactAddress'] = $legalContactAddress;

        return $this;
    }

    /**
     * Gets legalCardCreateUnit
     *
     * @return string
     */
    public function getLegalCardCreateUnit()
    {
        return $this->container['legalCardCreateUnit'];
    }

    /**
     * Sets legalCardCreateUnit
     *
     * @param string $legalCardCreateUnit <p>法人证件发证机关</p>
     *
     * @return $this
     */
    public function setLegalCardCreateUnit($legalCardCreateUnit)
    {
        $this->container['legalCardCreateUnit'] = $legalCardCreateUnit;

        return $this;
    }

    /**
     * Gets legalLicenceEffectiveDate
     *
     * @return string
     */
    public function getLegalLicenceEffectiveDate()
    {
        return $this->container['legalLicenceEffectiveDate'];
    }

    /**
     * Sets legalLicenceEffectiveDate
     *
     * @param string $legalLicenceEffectiveDate <p>参数格式为yyyyMMdd</p>
     *
     * @return $this
     */
    public function setLegalLicenceEffectiveDate($legalLicenceEffectiveDate)
    {
        $this->container['legalLicenceEffectiveDate'] = $legalLicenceEffectiveDate;

        return $this;
    }

    /**
     * Gets legalLicenceExpirationDate
     *
     * @return string
     */
    public function getLegalLicenceExpirationDate()
    {
        return $this->container['legalLicenceExpirationDate'];
    }

    /**
     * Sets legalLicenceExpirationDate
     *
     * @param string $legalLicenceExpirationDate <p>参数格式为yyyyMMdd或者forever</p>
     *
     * @return $this
     */
    public function setLegalLicenceExpirationDate($legalLicenceExpirationDate)
    {
        $this->container['legalLicenceExpirationDate'] = $legalLicenceExpirationDate;

        return $this;
    }

    /**
     * Gets benefitInfoDTOList
     *
     * @return \Yeepay\Yop\Sdk\Service\Account\Model\WhLhbBenefitDTO[]
     */
    public function getBenefitInfoDTOList()
    {
        return $this->container['benefitInfoDTOList'];
    }

    /**
     * Sets benefitInfoDTOList
     *
     * @param \Yeepay\Yop\Sdk\Service\Account\Model\WhLhbBenefitDTO[] $benefitInfoDTOList <p>受益人信息用于银行开户审核使用，请如实填写。直接或间接控股人&gt;人事财务控制人&gt;高级管理人员&gt;法定代表人/负责人&gt;其他类型，按以上优先级进行上传，传入最高层级的全部受益人即可。</p> <p><br /><br /></p>
     *
     * @return $this
     */
    public function setBenefitInfoDTOList($benefitInfoDTOList)
    {
        $this->container['benefitInfoDTOList'] = $benefitInfoDTOList;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


