<?php
/**
 * BatchProxyTransferReqDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 账户
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Account\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * BatchProxyTransferReqDTO Class Doc Comment
 *
 * @category Class
 * @description 转账到支付宝请求参数
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BatchProxyTransferReqDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BatchProxyTransferReqDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'parentMerchantNo' => 'string',
        'merchantNo' => 'string',
        'batchNo' => 'string',
        'requestNo' => 'string',
        'totalCount' => 'int',
        'title' => 'string',
        'url' => 'string',
        'channelBookId' => 'string',
        'totalAmount' => 'string',
        'batchProxList' => '\Yeepay\Yop\Sdk\Service\Account\Model\SingleProxyTransferReqDTO[]',
        'batchBusinessNo' => 'string',
        'batchRemark' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'parentMerchantNo' => null,
        'merchantNo' => null,
        'batchNo' => null,
        'requestNo' => null,
        'totalCount' => 'int32',
        'title' => null,
        'url' => null,
        'channelBookId' => null,
        'totalAmount' => null,
        'batchProxList' => null,
        'batchBusinessNo' => null,
        'batchRemark' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'parentMerchantNo' => 'parentMerchantNo',
        'merchantNo' => 'merchantNo',
        'batchNo' => 'batchNo',
        'requestNo' => 'requestNo',
        'totalCount' => 'totalCount',
        'title' => 'title',
        'url' => 'url',
        'channelBookId' => 'channelBookId',
        'totalAmount' => 'totalAmount',
        'batchProxList' => 'batchProxList',
        'batchBusinessNo' => 'batchBusinessNo',
        'batchRemark' => 'batchRemark'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'parentMerchantNo' => 'setParentMerchantNo',
        'merchantNo' => 'setMerchantNo',
        'batchNo' => 'setBatchNo',
        'requestNo' => 'setRequestNo',
        'totalCount' => 'setTotalCount',
        'title' => 'setTitle',
        'url' => 'setUrl',
        'channelBookId' => 'setChannelBookId',
        'totalAmount' => 'setTotalAmount',
        'batchProxList' => 'setBatchProxList',
        'batchBusinessNo' => 'setBatchBusinessNo',
        'batchRemark' => 'setBatchRemark'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'parentMerchantNo' => 'getParentMerchantNo',
        'merchantNo' => 'getMerchantNo',
        'batchNo' => 'getBatchNo',
        'requestNo' => 'getRequestNo',
        'totalCount' => 'getTotalCount',
        'title' => 'getTitle',
        'url' => 'getUrl',
        'channelBookId' => 'getChannelBookId',
        'totalAmount' => 'getTotalAmount',
        'batchProxList' => 'getBatchProxList',
        'batchBusinessNo' => 'getBatchBusinessNo',
        'batchRemark' => 'getBatchRemark'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['parentMerchantNo'] = isset($data['parentMerchantNo']) ? $data['parentMerchantNo'] : null;
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
        $this->container['batchNo'] = isset($data['batchNo']) ? $data['batchNo'] : null;
        $this->container['requestNo'] = isset($data['requestNo']) ? $data['requestNo'] : null;
        $this->container['totalCount'] = isset($data['totalCount']) ? $data['totalCount'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['channelBookId'] = isset($data['channelBookId']) ? $data['channelBookId'] : null;
        $this->container['totalAmount'] = isset($data['totalAmount']) ? $data['totalAmount'] : null;
        $this->container['batchProxList'] = isset($data['batchProxList']) ? $data['batchProxList'] : null;
        $this->container['batchBusinessNo'] = isset($data['batchBusinessNo']) ? $data['batchBusinessNo'] : null;
        $this->container['batchRemark'] = isset($data['batchRemark']) ? $data['batchRemark'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['parentMerchantNo'] === null) {
            $invalidProperties[] = "'parentMerchantNo' can't be null";
        }
        if ($this->container['merchantNo'] === null) {
            $invalidProperties[] = "'merchantNo' can't be null";
        }
        if ($this->container['batchNo'] === null) {
            $invalidProperties[] = "'batchNo' can't be null";
        }
        if ($this->container['requestNo'] === null) {
            $invalidProperties[] = "'requestNo' can't be null";
        }
        if ($this->container['totalCount'] === null) {
            $invalidProperties[] = "'totalCount' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['channelBookId'] === null) {
            $invalidProperties[] = "'channelBookId' can't be null";
        }
        if ($this->container['totalAmount'] === null) {
            $invalidProperties[] = "'totalAmount' can't be null";
        }
        if ($this->container['batchProxList'] === null) {
            $invalidProperties[] = "'batchProxList' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets parentMerchantNo
     *
     * @return string
     */
    public function getParentMerchantNo()
    {
        return $this->container['parentMerchantNo'];
    }

    /**
     * Sets parentMerchantNo
     *
     * @param string $parentMerchantNo <p>*标准商户收付款方案中此参数与商户编号一致；*平台商户收付款方案中此参数为平台商商户编号；*服务商解决方案中，①商户编号属于标准商户时，该参数为服务商商编 ②商户编号属于平台商时，此参数填写服务商商户编号 ③商户编号属于平台商入驻商户时，该参数填写平台商商编</p>
     *
     * @return $this
     */
    public function setParentMerchantNo($parentMerchantNo)
    {
        $this->container['parentMerchantNo'] = $parentMerchantNo;

        return $this;
    }

    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo <p>商编</p>
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }

    /**
     * Gets batchNo
     *
     * @return string
     */
    public function getBatchNo()
    {
        return $this->container['batchNo'];
    }

    /**
     * Sets batchNo
     *
     * @param string $batchNo <p>批次号</p>
     *
     * @return $this
     */
    public function setBatchNo($batchNo)
    {
        $this->container['batchNo'] = $batchNo;

        return $this;
    }

    /**
     * Gets requestNo
     *
     * @return string
     */
    public function getRequestNo()
    {
        return $this->container['requestNo'];
    }

    /**
     * Sets requestNo
     *
     * @param string $requestNo <p>商户唯一请求号</p>
     *
     * @return $this
     */
    public function setRequestNo($requestNo)
    {
        $this->container['requestNo'] = $requestNo;

        return $this;
    }

    /**
     * Gets totalCount
     *
     * @return int
     */
    public function getTotalCount()
    {
        return $this->container['totalCount'];
    }

    /**
     * Sets totalCount
     *
     * @param int $totalCount <p>总数</p>
     *
     * @return $this
     */
    public function setTotalCount($totalCount)
    {
        $this->container['totalCount'] = $totalCount;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title <p>标题</p>
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url <p>回调地址</p>
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets channelBookId
     *
     * @return string
     */
    public function getChannelBookId()
    {
        return $this->container['channelBookId'];
    }

    /**
     * Sets channelBookId
     *
     * @param string $channelBookId <p>记账本编号</p>
     *
     * @return $this
     */
    public function setChannelBookId($channelBookId)
    {
        $this->container['channelBookId'] = $channelBookId;

        return $this;
    }

    /**
     * Gets totalAmount
     *
     * @return string
     */
    public function getTotalAmount()
    {
        return $this->container['totalAmount'];
    }

    /**
     * Sets totalAmount
     *
     * @param string $totalAmount <p>总金额</p>
     *
     * @return $this
     */
    public function setTotalAmount($totalAmount)
    {
        $this->container['totalAmount'] = $totalAmount;

        return $this;
    }

    /**
     * Gets batchProxList
     *
     * @return \Yeepay\Yop\Sdk\Service\Account\Model\SingleProxyTransferReqDTO[]
     */
    public function getBatchProxList()
    {
        return $this->container['batchProxList'];
    }

    /**
     * Sets batchProxList
     *
     * @param \Yeepay\Yop\Sdk\Service\Account\Model\SingleProxyTransferReqDTO[] $batchProxList <p>批次明细</p>
     *
     * @return $this
     */
    public function setBatchProxList($batchProxList)
    {
        $this->container['batchProxList'] = $batchProxList;

        return $this;
    }

    /**
     * Gets batchBusinessNo
     *
     * @return string
     */
    public function getBatchBusinessNo()
    {
        return $this->container['batchBusinessNo'];
    }

    /**
     * Sets batchBusinessNo
     *
     * @param string $batchBusinessNo <p>商户批次业务订单号</p>
     *
     * @return $this
     */
    public function setBatchBusinessNo($batchBusinessNo)
    {
        $this->container['batchBusinessNo'] = $batchBusinessNo;

        return $this;
    }

    /**
     * Gets batchRemark
     *
     * @return string
     */
    public function getBatchRemark()
    {
        return $this->container['batchRemark'];
    }

    /**
     * Sets batchRemark
     *
     * @param string $batchRemark <p>商户批次备注</p>
     *
     * @return $this
     */
    public function setBatchRemark($batchRemark)
    {
        $this->container['batchRemark'] = $batchRemark;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


