<?php
/**
 * RemitOrderReverseQueryRespDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 账户
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Account\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * RemitOrderReverseQueryRespDTO Class Doc Comment
 *
 * @category Class
 * @description 查询银行冲退响应
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RemitOrderReverseQueryRespDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RemitOrderReverseQueryRespDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'returnCode' => 'string',
        'returnMsg' => 'string',
        'totalSize' => 'int',
        'pageNo' => 'int',
        'pageSize' => 'int',
        'reverseDetailDTOList' => '\Yeepay\Yop\Sdk\Service\Account\Model\RemitOrderReverseDetailDTO[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'returnCode' => null,
        'returnMsg' => null,
        'totalSize' => 'int32',
        'pageNo' => 'int32',
        'pageSize' => 'int32',
        'reverseDetailDTOList' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'returnCode' => 'returnCode',
        'returnMsg' => 'returnMsg',
        'totalSize' => 'totalSize',
        'pageNo' => 'pageNo',
        'pageSize' => 'pageSize',
        'reverseDetailDTOList' => 'reverseDetailDTOList'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'returnCode' => 'setReturnCode',
        'returnMsg' => 'setReturnMsg',
        'totalSize' => 'setTotalSize',
        'pageNo' => 'setPageNo',
        'pageSize' => 'setPageSize',
        'reverseDetailDTOList' => 'setReverseDetailDTOList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'returnCode' => 'getReturnCode',
        'returnMsg' => 'getReturnMsg',
        'totalSize' => 'getTotalSize',
        'pageNo' => 'getPageNo',
        'pageSize' => 'getPageSize',
        'reverseDetailDTOList' => 'getReverseDetailDTOList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['returnCode'] = isset($data['returnCode']) ? $data['returnCode'] : null;
        $this->container['returnMsg'] = isset($data['returnMsg']) ? $data['returnMsg'] : null;
        $this->container['totalSize'] = isset($data['totalSize']) ? $data['totalSize'] : null;
        $this->container['pageNo'] = isset($data['pageNo']) ? $data['pageNo'] : null;
        $this->container['pageSize'] = isset($data['pageSize']) ? $data['pageSize'] : null;
        $this->container['reverseDetailDTOList'] = isset($data['reverseDetailDTOList']) ? $data['reverseDetailDTOList'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['returnCode'] === null) {
            $invalidProperties[] = "'returnCode' can't be null";
        }
        if ($this->container['returnMsg'] === null) {
            $invalidProperties[] = "'returnMsg' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets returnCode
     *
     * @return string
     */
    public function getReturnCode()
    {
        return $this->container['returnCode'];
    }

    /**
     * Sets returnCode
     *
     * @param string $returnCode <div data-page-id=\"ApHSdhxlLoo90DxJokbcj9ernCb\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-FS16daxD2oEivmxtCO1cCqjUnQb\">返回码</div> </div>
     *
     * @return $this
     */
    public function setReturnCode($returnCode)
    {
        $this->container['returnCode'] = $returnCode;

        return $this;
    }

    /**
     * Gets returnMsg
     *
     * @return string
     */
    public function getReturnMsg()
    {
        return $this->container['returnMsg'];
    }

    /**
     * Sets returnMsg
     *
     * @param string $returnMsg <div data-page-id=\"ApHSdhxlLoo90DxJokbcj9ernCb\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-XlqNdRmMKoLjyQxrcpscqRfwn9f\">返回信息</div> </div>
     *
     * @return $this
     */
    public function setReturnMsg($returnMsg)
    {
        $this->container['returnMsg'] = $returnMsg;

        return $this;
    }

    /**
     * Gets totalSize
     *
     * @return int
     */
    public function getTotalSize()
    {
        return $this->container['totalSize'];
    }

    /**
     * Sets totalSize
     *
     * @param int $totalSize <div data-page-id=\"ApHSdhxlLoo90DxJokbcj9ernCb\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-KNWDdS3pJoRj4Txsw8AcO3zQncb\">总笔数</div> </div>
     *
     * @return $this
     */
    public function setTotalSize($totalSize)
    {
        $this->container['totalSize'] = $totalSize;

        return $this;
    }

    /**
     * Gets pageNo
     *
     * @return int
     */
    public function getPageNo()
    {
        return $this->container['pageNo'];
    }

    /**
     * Sets pageNo
     *
     * @param int $pageNo <div data-page-id=\"ApHSdhxlLoo90DxJokbcj9ernCb\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-LsNkdEAf7o6ZKFxGunRcJAREnNe\">当前页码</div> </div>
     *
     * @return $this
     */
    public function setPageNo($pageNo)
    {
        $this->container['pageNo'] = $pageNo;

        return $this;
    }

    /**
     * Gets pageSize
     *
     * @return int
     */
    public function getPageSize()
    {
        return $this->container['pageSize'];
    }

    /**
     * Sets pageSize
     *
     * @param int $pageSize <div data-page-id=\"ApHSdhxlLoo90DxJokbcj9ernCb\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-FMVqd0qWhoIGiPxdNQRc7TVonER\">当前页大小</div> </div>
     *
     * @return $this
     */
    public function setPageSize($pageSize)
    {
        $this->container['pageSize'] = $pageSize;

        return $this;
    }

    /**
     * Gets reverseDetailDTOList
     *
     * @return \Yeepay\Yop\Sdk\Service\Account\Model\RemitOrderReverseDetailDTO[]
     */
    public function getReverseDetailDTOList()
    {
        return $this->container['reverseDetailDTOList'];
    }

    /**
     * Sets reverseDetailDTOList
     *
     * @param \Yeepay\Yop\Sdk\Service\Account\Model\RemitOrderReverseDetailDTO[] $reverseDetailDTOList <div data-page-id=\"ApHSdhxlLoo90DxJokbcj9ernCb\" data-lark-html-role=\"root\" data-docx-has-block-data=\"false\"> <div class=\"ace-line ace-line old-record-id-GyfLdlE8Lo5D6tx78pbcuFcnnhf\">明细列表</div> </div>
     *
     * @return $this
     */
    public function setReverseDetailDTOList($reverseDetailDTOList)
    {
        $this->container['reverseDetailDTOList'] = $reverseDetailDTOList;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


