<?php
/**
 * ApplyInvoiceYOPResponseDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 发票服务
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\Invoice\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * ApplyInvoiceYOPResponseDto Class Doc Comment
 *
 * @category Class
 * @description 响应结果
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApplyInvoiceYOPResponseDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ApplyInvoiceYOPResponseDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'merchantNo' => 'string',
        'customerRequestNo' => 'string',
        'code' => 'string',
        'message' => 'string',
        'status' => 'string',
        'createDate' => '\DateTime',
        'chargingDateStart' => '\DateTime',
        'chargingDateEnd' => '\DateTime',
        'chargingMode' => 'string',
        'invoiceForm' => 'string',
        'amount' => 'float',
        'notifyType' => 'string',
        'invoiceMajor' => 'string',
        'issueInvoiceDtoList' => '\Yeepay\Yop\Sdk\Service\Invoice\Model\IssueInvoiceDTO[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'merchantNo' => null,
        'customerRequestNo' => null,
        'code' => null,
        'message' => null,
        'status' => null,
        'createDate' => 'date-time',
        'chargingDateStart' => 'date-time',
        'chargingDateEnd' => 'date-time',
        'chargingMode' => null,
        'invoiceForm' => null,
        'amount' => null,
        'notifyType' => null,
        'invoiceMajor' => null,
        'issueInvoiceDtoList' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'merchantNo' => 'merchantNo',
        'customerRequestNo' => 'customerRequestNo',
        'code' => 'code',
        'message' => 'message',
        'status' => 'status',
        'createDate' => 'createDate',
        'chargingDateStart' => 'chargingDateStart',
        'chargingDateEnd' => 'chargingDateEnd',
        'chargingMode' => 'chargingMode',
        'invoiceForm' => 'invoiceForm',
        'amount' => 'amount',
        'notifyType' => 'notifyType',
        'invoiceMajor' => 'invoiceMajor',
        'issueInvoiceDtoList' => 'issueInvoiceDtoList'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'merchantNo' => 'setMerchantNo',
        'customerRequestNo' => 'setCustomerRequestNo',
        'code' => 'setCode',
        'message' => 'setMessage',
        'status' => 'setStatus',
        'createDate' => 'setCreateDate',
        'chargingDateStart' => 'setChargingDateStart',
        'chargingDateEnd' => 'setChargingDateEnd',
        'chargingMode' => 'setChargingMode',
        'invoiceForm' => 'setInvoiceForm',
        'amount' => 'setAmount',
        'notifyType' => 'setNotifyType',
        'invoiceMajor' => 'setInvoiceMajor',
        'issueInvoiceDtoList' => 'setIssueInvoiceDtoList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'merchantNo' => 'getMerchantNo',
        'customerRequestNo' => 'getCustomerRequestNo',
        'code' => 'getCode',
        'message' => 'getMessage',
        'status' => 'getStatus',
        'createDate' => 'getCreateDate',
        'chargingDateStart' => 'getChargingDateStart',
        'chargingDateEnd' => 'getChargingDateEnd',
        'chargingMode' => 'getChargingMode',
        'invoiceForm' => 'getInvoiceForm',
        'amount' => 'getAmount',
        'notifyType' => 'getNotifyType',
        'invoiceMajor' => 'getInvoiceMajor',
        'issueInvoiceDtoList' => 'getIssueInvoiceDtoList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
        $this->container['customerRequestNo'] = isset($data['customerRequestNo']) ? $data['customerRequestNo'] : null;
        $this->container['code'] = isset($data['code']) ? $data['code'] : null;
        $this->container['message'] = isset($data['message']) ? $data['message'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['createDate'] = isset($data['createDate']) ? $data['createDate'] : null;
        $this->container['chargingDateStart'] = isset($data['chargingDateStart']) ? $data['chargingDateStart'] : null;
        $this->container['chargingDateEnd'] = isset($data['chargingDateEnd']) ? $data['chargingDateEnd'] : null;
        $this->container['chargingMode'] = isset($data['chargingMode']) ? $data['chargingMode'] : null;
        $this->container['invoiceForm'] = isset($data['invoiceForm']) ? $data['invoiceForm'] : null;
        $this->container['amount'] = isset($data['amount']) ? $data['amount'] : null;
        $this->container['notifyType'] = isset($data['notifyType']) ? $data['notifyType'] : null;
        $this->container['invoiceMajor'] = isset($data['invoiceMajor']) ? $data['invoiceMajor'] : null;
        $this->container['issueInvoiceDtoList'] = isset($data['issueInvoiceDtoList']) ? $data['issueInvoiceDtoList'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['merchantNo'] === null) {
            $invalidProperties[] = "'merchantNo' can't be null";
        }
        if ($this->container['customerRequestNo'] === null) {
            $invalidProperties[] = "'customerRequestNo' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo <p>同步返参、异步返参都有</p>
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }

    /**
     * Gets customerRequestNo
     *
     * @return string
     */
    public function getCustomerRequestNo()
    {
        return $this->container['customerRequestNo'];
    }

    /**
     * Sets customerRequestNo
     *
     * @param string $customerRequestNo <p>同步返参、异步返参都有</p>
     *
     * @return $this
     */
    public function setCustomerRequestNo($customerRequestNo)
    {
        $this->container['customerRequestNo'] = $customerRequestNo;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code <p>同步返参</p>
     *
     * @return $this
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string $message <p>同步返参</p>
     *
     * @return $this
     */
    public function setMessage($message)
    {
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status <p>同步返参。开票成功的情况下返回SUCCESS，开票失败或出现异常的情况下返回FAIL。</p>
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets createDate
     *
     * @return \DateTime
     */
    public function getCreateDate()
    {
        return $this->container['createDate'];
    }

    /**
     * Sets createDate
     *
     * @param \DateTime $createDate <p>异步返参</p>
     *
     * @return $this
     */
    public function setCreateDate($createDate)
    {
        $this->container['createDate'] = $createDate;

        return $this;
    }

    /**
     * Gets chargingDateStart
     *
     * @return \DateTime
     */
    public function getChargingDateStart()
    {
        return $this->container['chargingDateStart'];
    }

    /**
     * Sets chargingDateStart
     *
     * @param \DateTime $chargingDateStart <p>异步返参</p>
     *
     * @return $this
     */
    public function setChargingDateStart($chargingDateStart)
    {
        $this->container['chargingDateStart'] = $chargingDateStart;

        return $this;
    }

    /**
     * Gets chargingDateEnd
     *
     * @return \DateTime
     */
    public function getChargingDateEnd()
    {
        return $this->container['chargingDateEnd'];
    }

    /**
     * Sets chargingDateEnd
     *
     * @param \DateTime $chargingDateEnd <p>异步返参</p>
     *
     * @return $this
     */
    public function setChargingDateEnd($chargingDateEnd)
    {
        $this->container['chargingDateEnd'] = $chargingDateEnd;

        return $this;
    }

    /**
     * Gets chargingMode
     *
     * @return string
     */
    public function getChargingMode()
    {
        return $this->container['chargingMode'];
    }

    /**
     * Sets chargingMode
     *
     * @param string $chargingMode <p>异步返参<br />可选项如下:<br />REAL_TIME:实收<br />UN_REAL_TIME:后收<br />PREPAID_REAL:预付实扣</p>
     *
     * @return $this
     */
    public function setChargingMode($chargingMode)
    {
        $this->container['chargingMode'] = $chargingMode;

        return $this;
    }

    /**
     * Gets invoiceForm
     *
     * @return string
     */
    public function getInvoiceForm()
    {
        return $this->container['invoiceForm'];
    }

    /**
     * Sets invoiceForm
     *
     * @param string $invoiceForm <p>异步返参<br />可选项如下:<br />E_INVOICE:电子发票<br />P_INVOICE:纸质发票</p>
     *
     * @return $this
     */
    public function setInvoiceForm($invoiceForm)
    {
        $this->container['invoiceForm'] = $invoiceForm;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float $amount <p>异步返参，字段类型及长度：decimal(12,2)</p>
     *
     * @return $this
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets notifyType
     *
     * @return string
     */
    public function getNotifyType()
    {
        return $this->container['notifyType'];
    }

    /**
     * Sets notifyType
     *
     * @param string $notifyType <p>异步返参，用于区分异步返参，申请、冲红、或取消发票<br />可选项如下:<br />NOTIFY_APPLY:申请开票异步通知<br />NOTIFY_CANCEL:取消开票异步通知<br />NOTIFY_CORRECT:冲红发票异步通知<br />NOTIFY_QUERY:查询开票记录</p>
     *
     * @return $this
     */
    public function setNotifyType($notifyType)
    {
        $this->container['notifyType'] = $notifyType;

        return $this;
    }

    /**
     * Gets invoiceMajor
     *
     * @return string
     */
    public function getInvoiceMajor()
    {
        return $this->container['invoiceMajor'];
    }

    /**
     * Sets invoiceMajor
     *
     * @param string $invoiceMajor <div data-page-id=\"QnlZd5qvsogo1Axs1KUcziXYnAh\" data-lark-html-role=\"root\" data-docx-has-block-data=\"true\"> <div> <table class=\"ace-table\" data-ace-table-col-widths=\"321\"><colgroup><col width=\"321\" /></colgroup> <tbody> <tr> <td colspan=\"1\" rowspan=\"1\"> <div class=\"ace-line ace-line old-record-id-FjePdG23DoE4HSx4tnwcELcBnCd\">发票开具方：</div> <div class=\"ace-line ace-line old-record-id-FjePdG23DoE4HSx4tnwcELcBnCd\">YP-易宝支付;</div> <div class=\"ace-line ace-line old-record-id-FjePdG23DoE4HSx4tnwcELcBnCd\">QQYX-麒麒远行</div> </td> </tr> </tbody> </table> </div> </div>
     *
     * @return $this
     */
    public function setInvoiceMajor($invoiceMajor)
    {
        $this->container['invoiceMajor'] = $invoiceMajor;

        return $this;
    }

    /**
     * Gets issueInvoiceDtoList
     *
     * @return \Yeepay\Yop\Sdk\Service\Invoice\Model\IssueInvoiceDTO[]
     */
    public function getIssueInvoiceDtoList()
    {
        return $this->container['issueInvoiceDtoList'];
    }

    /**
     * Sets issueInvoiceDtoList
     *
     * @param \Yeepay\Yop\Sdk\Service\Invoice\Model\IssueInvoiceDTO[] $issueInvoiceDtoList <p>异步返参</p>
     *
     * @return $this
     */
    public function setIssueInvoiceDtoList($issueInvoiceDtoList)
    {
        $this->container['issueInvoiceDtoList'] = $issueInvoiceDtoList;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


