<?php
/**
 * YopMultiChannelQueryWithholdRecordResDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 代运营服务
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yeepay\Yop\Sdk\Service\AgencyOperation\Model;

use \ArrayAccess;
use Yeepay\Yop\Sdk\Model\ModelInterface;
use Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * YopMultiChannelQueryWithholdRecordResDTO Class Doc Comment
 *
 * @category Class
 * @description 抽佣记录查询结果
 * @package  Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class YopMultiChannelQueryWithholdRecordResDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'YopMultiChannelQueryWithholdRecordResDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'contributeMerchantNo' => 'string',
        'receiveMerchantNo' => 'string',
        'requestNo' => 'string',
        'status' => 'string',
        'fee' => 'float',
        'ypSettleAmount' => 'float',
        'withholdAmount' => 'float',
        'failReason' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'contributeMerchantNo' => null,
        'receiveMerchantNo' => null,
        'requestNo' => null,
        'status' => null,
        'fee' => null,
        'ypSettleAmount' => null,
        'withholdAmount' => null,
        'failReason' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'contributeMerchantNo' => 'contributeMerchantNo',
        'receiveMerchantNo' => 'receiveMerchantNo',
        'requestNo' => 'requestNo',
        'status' => 'status',
        'fee' => 'fee',
        'ypSettleAmount' => 'ypSettleAmount',
        'withholdAmount' => 'withholdAmount',
        'failReason' => 'failReason'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'contributeMerchantNo' => 'setContributeMerchantNo',
        'receiveMerchantNo' => 'setReceiveMerchantNo',
        'requestNo' => 'setRequestNo',
        'status' => 'setStatus',
        'fee' => 'setFee',
        'ypSettleAmount' => 'setYpSettleAmount',
        'withholdAmount' => 'setWithholdAmount',
        'failReason' => 'setFailReason'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'contributeMerchantNo' => 'getContributeMerchantNo',
        'receiveMerchantNo' => 'getReceiveMerchantNo',
        'requestNo' => 'getRequestNo',
        'status' => 'getStatus',
        'fee' => 'getFee',
        'ypSettleAmount' => 'getYpSettleAmount',
        'withholdAmount' => 'getWithholdAmount',
        'failReason' => 'getFailReason'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['contributeMerchantNo'] = isset($data['contributeMerchantNo']) ? $data['contributeMerchantNo'] : null;
        $this->container['receiveMerchantNo'] = isset($data['receiveMerchantNo']) ? $data['receiveMerchantNo'] : null;
        $this->container['requestNo'] = isset($data['requestNo']) ? $data['requestNo'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['fee'] = isset($data['fee']) ? $data['fee'] : null;
        $this->container['ypSettleAmount'] = isset($data['ypSettleAmount']) ? $data['ypSettleAmount'] : null;
        $this->container['withholdAmount'] = isset($data['withholdAmount']) ? $data['withholdAmount'] : null;
        $this->container['failReason'] = isset($data['failReason']) ? $data['failReason'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['contributeMerchantNo'] === null) {
            $invalidProperties[] = "'contributeMerchantNo' can't be null";
        }
        if ($this->container['receiveMerchantNo'] === null) {
            $invalidProperties[] = "'receiveMerchantNo' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets contributeMerchantNo
     *
     * @return string
     */
    public function getContributeMerchantNo()
    {
        return $this->container['contributeMerchantNo'];
    }

    /**
     * Sets contributeMerchantNo
     *
     * @param string $contributeMerchantNo <p>被抽佣方商编</p>
     *
     * @return $this
     */
    public function setContributeMerchantNo($contributeMerchantNo)
    {
        $this->container['contributeMerchantNo'] = $contributeMerchantNo;

        return $this;
    }

    /**
     * Gets receiveMerchantNo
     *
     * @return string
     */
    public function getReceiveMerchantNo()
    {
        return $this->container['receiveMerchantNo'];
    }

    /**
     * Sets receiveMerchantNo
     *
     * @param string $receiveMerchantNo <p>抽佣接收方商编</p>
     *
     * @return $this
     */
    public function setReceiveMerchantNo($receiveMerchantNo)
    {
        $this->container['receiveMerchantNo'] = $receiveMerchantNo;

        return $this;
    }

    /**
     * Gets requestNo
     *
     * @return string
     */
    public function getRequestNo()
    {
        return $this->container['requestNo'];
    }

    /**
     * Sets requestNo
     *
     * @param string $requestNo <p>请求号</p>
     *
     * @return $this
     */
    public function setRequestNo($requestNo)
    {
        $this->container['requestNo'] = $requestNo;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status <p>抽佣状态</p> <p>PROCESSING ： 处理中</p> <p>FAIL ：失败</p> <p>SUCCESS : 成功</p>
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets fee
     *
     * @return float
     */
    public function getFee()
    {
        return $this->container['fee'];
    }

    /**
     * Sets fee
     *
     * @param float $fee <p>手续费</p>
     *
     * @return $this
     */
    public function setFee($fee)
    {
        $this->container['fee'] = $fee;

        return $this;
    }

    /**
     * Gets ypSettleAmount
     *
     * @return float
     */
    public function getYpSettleAmount()
    {
        return $this->container['ypSettleAmount'];
    }

    /**
     * Sets ypSettleAmount
     *
     * @param float $ypSettleAmount <p>入账金额</p>
     *
     * @return $this
     */
    public function setYpSettleAmount($ypSettleAmount)
    {
        $this->container['ypSettleAmount'] = $ypSettleAmount;

        return $this;
    }

    /**
     * Gets withholdAmount
     *
     * @return float
     */
    public function getWithholdAmount()
    {
        return $this->container['withholdAmount'];
    }

    /**
     * Sets withholdAmount
     *
     * @param float $withholdAmount <p>抽佣金额</p>
     *
     * @return $this
     */
    public function setWithholdAmount($withholdAmount)
    {
        $this->container['withholdAmount'] = $withholdAmount;

        return $this;
    }

    /**
     * Gets failReason
     *
     * @return string
     */
    public function getFailReason()
    {
        return $this->container['failReason'];
    }

    /**
     * Sets failReason
     *
     * @param string $failReason <p>失败原因</p>
     *
     * @return $this
     */
    public function setFailReason($failReason)
    {
        $this->container['failReason'] = $failReason;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


